// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/common/transactionReceipt/TransactionReceiptDto.proto

package org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt;

/**
 * Protobuf type {@code org.qsn.protobuf.TransactionReceiptDto}
 */
public final class TransactionReceiptDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.TransactionReceiptDto)
    TransactionReceiptDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionReceiptDto.newBuilder() to construct.
  private TransactionReceiptDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionReceiptDto() {
    blockHash_ = com.google.protobuf.ByteString.EMPTY;
    transactionHash_ = com.google.protobuf.ByteString.EMPTY;
    sender_ = com.google.protobuf.ByteString.EMPTY;
    contractAddress_ = com.google.protobuf.ByteString.EMPTY;
    contractAction_ = com.google.protobuf.ByteString.EMPTY;
    logs_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionReceiptDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionReceiptDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            blockHash_ = input.readBytes();
            break;
          }
          case 18: {
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder subBuilder = null;
            if (blockHeight_ != null) {
              subBuilder = blockHeight_.toBuilder();
            }
            blockHeight_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.BInteger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(blockHeight_);
              blockHeight_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {

            transactionHash_ = input.readBytes();
            break;
          }
          case 32: {

            transactionIndex_ = input.readInt32();
            break;
          }
          case 42: {

            sender_ = input.readBytes();
            break;
          }
          case 50: {
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder subBuilder = null;
            if (feeUsed_ != null) {
              subBuilder = feeUsed_.toBuilder();
            }
            feeUsed_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.BInteger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(feeUsed_);
              feeUsed_ = subBuilder.buildPartial();
            }

            break;
          }
          case 56: {

            status_ = input.readInt32();
            break;
          }
          case 66: {

            contractAddress_ = input.readBytes();
            break;
          }
          case 74: {

            contractAction_ = input.readBytes();
            break;
          }
          case 82: {

            logs_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDtoOuterClass.internal_static_org_qsn_protobuf_TransactionReceiptDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDtoOuterClass.internal_static_org_qsn_protobuf_TransactionReceiptDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.class, org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.Builder.class);
  }

  public static final int BLOCKHASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString blockHash_;
  /**
   * <code>bytes blockHash = 1;</code>
   * @return The blockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBlockHash() {
    return blockHash_;
  }

  public static final int BLOCKHEIGHT_FIELD_NUMBER = 2;
  private org.qsn.api.rpc.grpc.proto.entity.common.BInteger blockHeight_;
  /**
   * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
   * @return Whether the blockHeight field is set.
   */
  @java.lang.Override
  public boolean hasBlockHeight() {
    return blockHeight_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
   * @return The blockHeight.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BInteger getBlockHeight() {
    return blockHeight_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : blockHeight_;
  }
  /**
   * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getBlockHeightOrBuilder() {
    return getBlockHeight();
  }

  public static final int TRANSACTIONHASH_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString transactionHash_;
  /**
   * <code>bytes transactionHash = 3;</code>
   * @return The transactionHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTransactionHash() {
    return transactionHash_;
  }

  public static final int TRANSACTIONINDEX_FIELD_NUMBER = 4;
  private int transactionIndex_;
  /**
   * <code>int32 transactionIndex = 4;</code>
   * @return The transactionIndex.
   */
  @java.lang.Override
  public int getTransactionIndex() {
    return transactionIndex_;
  }

  public static final int SENDER_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString sender_;
  /**
   * <code>bytes sender = 5;</code>
   * @return The sender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSender() {
    return sender_;
  }

  public static final int FEEUSED_FIELD_NUMBER = 6;
  private org.qsn.api.rpc.grpc.proto.entity.common.BInteger feeUsed_;
  /**
   * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
   * @return Whether the feeUsed field is set.
   */
  @java.lang.Override
  public boolean hasFeeUsed() {
    return feeUsed_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
   * @return The feeUsed.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BInteger getFeeUsed() {
    return feeUsed_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : feeUsed_;
  }
  /**
   * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getFeeUsedOrBuilder() {
    return getFeeUsed();
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  private int status_;
  /**
   * <code>int32 status = 7;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int CONTRACTADDRESS_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString contractAddress_;
  /**
   * <code>bytes contractAddress = 8;</code>
   * @return The contractAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContractAddress() {
    return contractAddress_;
  }

  public static final int CONTRACTACTION_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString contractAction_;
  /**
   * <code>bytes contractAction = 9;</code>
   * @return The contractAction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContractAction() {
    return contractAction_;
  }

  public static final int LOGS_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString logs_;
  /**
   * <code>bytes logs = 10;</code>
   * @return The logs.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLogs() {
    return logs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!blockHash_.isEmpty()) {
      output.writeBytes(1, blockHash_);
    }
    if (blockHeight_ != null) {
      output.writeMessage(2, getBlockHeight());
    }
    if (!transactionHash_.isEmpty()) {
      output.writeBytes(3, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      output.writeInt32(4, transactionIndex_);
    }
    if (!sender_.isEmpty()) {
      output.writeBytes(5, sender_);
    }
    if (feeUsed_ != null) {
      output.writeMessage(6, getFeeUsed());
    }
    if (status_ != 0) {
      output.writeInt32(7, status_);
    }
    if (!contractAddress_.isEmpty()) {
      output.writeBytes(8, contractAddress_);
    }
    if (!contractAction_.isEmpty()) {
      output.writeBytes(9, contractAction_);
    }
    if (!logs_.isEmpty()) {
      output.writeBytes(10, logs_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!blockHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, blockHash_);
    }
    if (blockHeight_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBlockHeight());
    }
    if (!transactionHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, transactionIndex_);
    }
    if (!sender_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, sender_);
    }
    if (feeUsed_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFeeUsed());
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, status_);
    }
    if (!contractAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, contractAddress_);
    }
    if (!contractAction_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, contractAction_);
    }
    if (!logs_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, logs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto other = (org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto) obj;

    if (!getBlockHash()
        .equals(other.getBlockHash())) return false;
    if (hasBlockHeight() != other.hasBlockHeight()) return false;
    if (hasBlockHeight()) {
      if (!getBlockHeight()
          .equals(other.getBlockHeight())) return false;
    }
    if (!getTransactionHash()
        .equals(other.getTransactionHash())) return false;
    if (getTransactionIndex()
        != other.getTransactionIndex()) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (hasFeeUsed() != other.hasFeeUsed()) return false;
    if (hasFeeUsed()) {
      if (!getFeeUsed()
          .equals(other.getFeeUsed())) return false;
    }
    if (getStatus()
        != other.getStatus()) return false;
    if (!getContractAddress()
        .equals(other.getContractAddress())) return false;
    if (!getContractAction()
        .equals(other.getContractAction())) return false;
    if (!getLogs()
        .equals(other.getLogs())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHash().hashCode();
    if (hasBlockHeight()) {
      hash = (37 * hash) + BLOCKHEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHeight().hashCode();
    }
    hash = (37 * hash) + TRANSACTIONHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionHash().hashCode();
    hash = (37 * hash) + TRANSACTIONINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionIndex();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    if (hasFeeUsed()) {
      hash = (37 * hash) + FEEUSED_FIELD_NUMBER;
      hash = (53 * hash) + getFeeUsed().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + CONTRACTADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getContractAddress().hashCode();
    hash = (37 * hash) + CONTRACTACTION_FIELD_NUMBER;
    hash = (53 * hash) + getContractAction().hashCode();
    hash = (37 * hash) + LOGS_FIELD_NUMBER;
    hash = (53 * hash) + getLogs().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.TransactionReceiptDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.TransactionReceiptDto)
      org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDtoOuterClass.internal_static_org_qsn_protobuf_TransactionReceiptDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDtoOuterClass.internal_static_org_qsn_protobuf_TransactionReceiptDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.class, org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      blockHash_ = com.google.protobuf.ByteString.EMPTY;

      if (blockHeightBuilder_ == null) {
        blockHeight_ = null;
      } else {
        blockHeight_ = null;
        blockHeightBuilder_ = null;
      }
      transactionHash_ = com.google.protobuf.ByteString.EMPTY;

      transactionIndex_ = 0;

      sender_ = com.google.protobuf.ByteString.EMPTY;

      if (feeUsedBuilder_ == null) {
        feeUsed_ = null;
      } else {
        feeUsed_ = null;
        feeUsedBuilder_ = null;
      }
      status_ = 0;

      contractAddress_ = com.google.protobuf.ByteString.EMPTY;

      contractAction_ = com.google.protobuf.ByteString.EMPTY;

      logs_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDtoOuterClass.internal_static_org_qsn_protobuf_TransactionReceiptDto_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto build() {
      org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto result = new org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto(this);
      result.blockHash_ = blockHash_;
      if (blockHeightBuilder_ == null) {
        result.blockHeight_ = blockHeight_;
      } else {
        result.blockHeight_ = blockHeightBuilder_.build();
      }
      result.transactionHash_ = transactionHash_;
      result.transactionIndex_ = transactionIndex_;
      result.sender_ = sender_;
      if (feeUsedBuilder_ == null) {
        result.feeUsed_ = feeUsed_;
      } else {
        result.feeUsed_ = feeUsedBuilder_.build();
      }
      result.status_ = status_;
      result.contractAddress_ = contractAddress_;
      result.contractAction_ = contractAction_;
      result.logs_ = logs_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto.getDefaultInstance()) return this;
      if (other.getBlockHash() != com.google.protobuf.ByteString.EMPTY) {
        setBlockHash(other.getBlockHash());
      }
      if (other.hasBlockHeight()) {
        mergeBlockHeight(other.getBlockHeight());
      }
      if (other.getTransactionHash() != com.google.protobuf.ByteString.EMPTY) {
        setTransactionHash(other.getTransactionHash());
      }
      if (other.getTransactionIndex() != 0) {
        setTransactionIndex(other.getTransactionIndex());
      }
      if (other.getSender() != com.google.protobuf.ByteString.EMPTY) {
        setSender(other.getSender());
      }
      if (other.hasFeeUsed()) {
        mergeFeeUsed(other.getFeeUsed());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getContractAddress() != com.google.protobuf.ByteString.EMPTY) {
        setContractAddress(other.getContractAddress());
      }
      if (other.getContractAction() != com.google.protobuf.ByteString.EMPTY) {
        setContractAction(other.getContractAction());
      }
      if (other.getLogs() != com.google.protobuf.ByteString.EMPTY) {
        setLogs(other.getLogs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString blockHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes blockHash = 1;</code>
     * @return The blockHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBlockHash() {
      return blockHash_;
    }
    /**
     * <code>bytes blockHash = 1;</code>
     * @param value The blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes blockHash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHash() {
      
      blockHash_ = getDefaultInstance().getBlockHash();
      onChanged();
      return this;
    }

    private org.qsn.api.rpc.grpc.proto.entity.common.BInteger blockHeight_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder> blockHeightBuilder_;
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     * @return Whether the blockHeight field is set.
     */
    public boolean hasBlockHeight() {
      return blockHeightBuilder_ != null || blockHeight_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     * @return The blockHeight.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BInteger getBlockHeight() {
      if (blockHeightBuilder_ == null) {
        return blockHeight_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : blockHeight_;
      } else {
        return blockHeightBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    public Builder setBlockHeight(org.qsn.api.rpc.grpc.proto.entity.common.BInteger value) {
      if (blockHeightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        blockHeight_ = value;
        onChanged();
      } else {
        blockHeightBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    public Builder setBlockHeight(
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder builderForValue) {
      if (blockHeightBuilder_ == null) {
        blockHeight_ = builderForValue.build();
        onChanged();
      } else {
        blockHeightBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    public Builder mergeBlockHeight(org.qsn.api.rpc.grpc.proto.entity.common.BInteger value) {
      if (blockHeightBuilder_ == null) {
        if (blockHeight_ != null) {
          blockHeight_ =
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.newBuilder(blockHeight_).mergeFrom(value).buildPartial();
        } else {
          blockHeight_ = value;
        }
        onChanged();
      } else {
        blockHeightBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    public Builder clearBlockHeight() {
      if (blockHeightBuilder_ == null) {
        blockHeight_ = null;
        onChanged();
      } else {
        blockHeight_ = null;
        blockHeightBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder getBlockHeightBuilder() {
      
      onChanged();
      return getBlockHeightFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getBlockHeightOrBuilder() {
      if (blockHeightBuilder_ != null) {
        return blockHeightBuilder_.getMessageOrBuilder();
      } else {
        return blockHeight_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : blockHeight_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.BInteger blockHeight = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder> 
        getBlockHeightFieldBuilder() {
      if (blockHeightBuilder_ == null) {
        blockHeightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder>(
                getBlockHeight(),
                getParentForChildren(),
                isClean());
        blockHeight_ = null;
      }
      return blockHeightBuilder_;
    }

    private com.google.protobuf.ByteString transactionHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes transactionHash = 3;</code>
     * @return The transactionHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTransactionHash() {
      return transactionHash_;
    }
    /**
     * <code>bytes transactionHash = 3;</code>
     * @param value The transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes transactionHash = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionHash() {
      
      transactionHash_ = getDefaultInstance().getTransactionHash();
      onChanged();
      return this;
    }

    private int transactionIndex_ ;
    /**
     * <code>int32 transactionIndex = 4;</code>
     * @return The transactionIndex.
     */
    @java.lang.Override
    public int getTransactionIndex() {
      return transactionIndex_;
    }
    /**
     * <code>int32 transactionIndex = 4;</code>
     * @param value The transactionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIndex(int value) {
      
      transactionIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transactionIndex = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionIndex() {
      
      transactionIndex_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString sender_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes sender = 5;</code>
     * @return The sender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSender() {
      return sender_;
    }
    /**
     * <code>bytes sender = 5;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes sender = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }

    private org.qsn.api.rpc.grpc.proto.entity.common.BInteger feeUsed_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder> feeUsedBuilder_;
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     * @return Whether the feeUsed field is set.
     */
    public boolean hasFeeUsed() {
      return feeUsedBuilder_ != null || feeUsed_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     * @return The feeUsed.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BInteger getFeeUsed() {
      if (feeUsedBuilder_ == null) {
        return feeUsed_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : feeUsed_;
      } else {
        return feeUsedBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    public Builder setFeeUsed(org.qsn.api.rpc.grpc.proto.entity.common.BInteger value) {
      if (feeUsedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        feeUsed_ = value;
        onChanged();
      } else {
        feeUsedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    public Builder setFeeUsed(
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder builderForValue) {
      if (feeUsedBuilder_ == null) {
        feeUsed_ = builderForValue.build();
        onChanged();
      } else {
        feeUsedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    public Builder mergeFeeUsed(org.qsn.api.rpc.grpc.proto.entity.common.BInteger value) {
      if (feeUsedBuilder_ == null) {
        if (feeUsed_ != null) {
          feeUsed_ =
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.newBuilder(feeUsed_).mergeFrom(value).buildPartial();
        } else {
          feeUsed_ = value;
        }
        onChanged();
      } else {
        feeUsedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    public Builder clearFeeUsed() {
      if (feeUsedBuilder_ == null) {
        feeUsed_ = null;
        onChanged();
      } else {
        feeUsed_ = null;
        feeUsedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder getFeeUsedBuilder() {
      
      onChanged();
      return getFeeUsedFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getFeeUsedOrBuilder() {
      if (feeUsedBuilder_ != null) {
        return feeUsedBuilder_.getMessageOrBuilder();
      } else {
        return feeUsed_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : feeUsed_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.BInteger feeUsed = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder> 
        getFeeUsedFieldBuilder() {
      if (feeUsedBuilder_ == null) {
        feeUsedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder>(
                getFeeUsed(),
                getParentForChildren(),
                isClean());
        feeUsed_ = null;
      }
      return feeUsedBuilder_;
    }

    private int status_ ;
    /**
     * <code>int32 status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString contractAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes contractAddress = 8;</code>
     * @return The contractAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContractAddress() {
      return contractAddress_;
    }
    /**
     * <code>bytes contractAddress = 8;</code>
     * @param value The contractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setContractAddress(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes contractAddress = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractAddress() {
      
      contractAddress_ = getDefaultInstance().getContractAddress();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString contractAction_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes contractAction = 9;</code>
     * @return The contractAction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContractAction() {
      return contractAction_;
    }
    /**
     * <code>bytes contractAction = 9;</code>
     * @param value The contractAction to set.
     * @return This builder for chaining.
     */
    public Builder setContractAction(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractAction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes contractAction = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractAction() {
      
      contractAction_ = getDefaultInstance().getContractAction();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString logs_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes logs = 10;</code>
     * @return The logs.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLogs() {
      return logs_;
    }
    /**
     * <code>bytes logs = 10;</code>
     * @param value The logs to set.
     * @return This builder for chaining.
     */
    public Builder setLogs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      logs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes logs = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogs() {
      
      logs_ = getDefaultInstance().getLogs();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.TransactionReceiptDto)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.TransactionReceiptDto)
  private static final org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionReceiptDto>
      PARSER = new com.google.protobuf.AbstractParser<TransactionReceiptDto>() {
    @java.lang.Override
    public TransactionReceiptDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionReceiptDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionReceiptDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionReceiptDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.transactionReceipt.TransactionReceiptDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

