// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/customized/BlockRewardTxDataDto.proto

package org.qsn.api.rpc.grpc.proto.entity.customized;

public interface BlockRewardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.qsn.protobuf.BlockReward)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 blockHeight = 1;</code>
   * @return The blockHeight.
   */
  long getBlockHeight();

  /**
   * <code>int64 matureHeight = 2;</code>
   * @return The matureHeight.
   */
  long getMatureHeight();

  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardData blockRewardDataList = 3;</code>
   */
  java.util.List<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardData> 
      getBlockRewardDataListList();
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardData blockRewardDataList = 3;</code>
   */
  org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardData getBlockRewardDataList(int index);
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardData blockRewardDataList = 3;</code>
   */
  int getBlockRewardDataListCount();
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardData blockRewardDataList = 3;</code>
   */
  java.util.List<? extends org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataOrBuilder> 
      getBlockRewardDataListOrBuilderList();
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardData blockRewardDataList = 3;</code>
   */
  org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataOrBuilder getBlockRewardDataListOrBuilder(
      int index);
}
