// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/customized/BlockRewardTxDataDto.proto

package org.qsn.api.rpc.grpc.proto.entity.customized;

/**
 * Protobuf type {@code org.qsn.protobuf.BlockRewardDto}
 */
public final class BlockRewardDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.BlockRewardDto)
    BlockRewardDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockRewardDto.newBuilder() to construct.
  private BlockRewardDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockRewardDto() {
    blockRewardDataList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockRewardDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BlockRewardDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            blockHeight_ = input.readInt64();
            break;
          }
          case 16: {

            matureHeight_ = input.readInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              blockRewardDataList_ = new java.util.ArrayList<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto>();
              mutable_bitField0_ |= 0x00000001;
            }
            blockRewardDataList_.add(
                input.readMessage(org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        blockRewardDataList_ = java.util.Collections.unmodifiableList(blockRewardDataList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardTxDataDtoOuterClass.internal_static_org_qsn_protobuf_BlockRewardDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardTxDataDtoOuterClass.internal_static_org_qsn_protobuf_BlockRewardDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.class, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.Builder.class);
  }

  public static final int BLOCKHEIGHT_FIELD_NUMBER = 1;
  private long blockHeight_;
  /**
   * <code>int64 blockHeight = 1;</code>
   * @return The blockHeight.
   */
  @java.lang.Override
  public long getBlockHeight() {
    return blockHeight_;
  }

  public static final int MATUREHEIGHT_FIELD_NUMBER = 2;
  private long matureHeight_;
  /**
   * <code>int64 matureHeight = 2;</code>
   * @return The matureHeight.
   */
  @java.lang.Override
  public long getMatureHeight() {
    return matureHeight_;
  }

  public static final int BLOCKREWARDDATALIST_FIELD_NUMBER = 3;
  private java.util.List<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto> blockRewardDataList_;
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto> getBlockRewardDataListList() {
    return blockRewardDataList_;
  }
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder> 
      getBlockRewardDataListOrBuilderList() {
    return blockRewardDataList_;
  }
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
   */
  @java.lang.Override
  public int getBlockRewardDataListCount() {
    return blockRewardDataList_.size();
  }
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto getBlockRewardDataList(int index) {
    return blockRewardDataList_.get(index);
  }
  /**
   * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder getBlockRewardDataListOrBuilder(
      int index) {
    return blockRewardDataList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blockHeight_ != 0L) {
      output.writeInt64(1, blockHeight_);
    }
    if (matureHeight_ != 0L) {
      output.writeInt64(2, matureHeight_);
    }
    for (int i = 0; i < blockRewardDataList_.size(); i++) {
      output.writeMessage(3, blockRewardDataList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blockHeight_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, blockHeight_);
    }
    if (matureHeight_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, matureHeight_);
    }
    for (int i = 0; i < blockRewardDataList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, blockRewardDataList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto other = (org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto) obj;

    if (getBlockHeight()
        != other.getBlockHeight()) return false;
    if (getMatureHeight()
        != other.getMatureHeight()) return false;
    if (!getBlockRewardDataListList()
        .equals(other.getBlockRewardDataListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCKHEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockHeight());
    hash = (37 * hash) + MATUREHEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMatureHeight());
    if (getBlockRewardDataListCount() > 0) {
      hash = (37 * hash) + BLOCKREWARDDATALIST_FIELD_NUMBER;
      hash = (53 * hash) + getBlockRewardDataListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.BlockRewardDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.BlockRewardDto)
      org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardTxDataDtoOuterClass.internal_static_org_qsn_protobuf_BlockRewardDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardTxDataDtoOuterClass.internal_static_org_qsn_protobuf_BlockRewardDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.class, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBlockRewardDataListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      blockHeight_ = 0L;

      matureHeight_ = 0L;

      if (blockRewardDataListBuilder_ == null) {
        blockRewardDataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        blockRewardDataListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardTxDataDtoOuterClass.internal_static_org_qsn_protobuf_BlockRewardDto_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto build() {
      org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto result = new org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto(this);
      int from_bitField0_ = bitField0_;
      result.blockHeight_ = blockHeight_;
      result.matureHeight_ = matureHeight_;
      if (blockRewardDataListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          blockRewardDataList_ = java.util.Collections.unmodifiableList(blockRewardDataList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.blockRewardDataList_ = blockRewardDataList_;
      } else {
        result.blockRewardDataList_ = blockRewardDataListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto.getDefaultInstance()) return this;
      if (other.getBlockHeight() != 0L) {
        setBlockHeight(other.getBlockHeight());
      }
      if (other.getMatureHeight() != 0L) {
        setMatureHeight(other.getMatureHeight());
      }
      if (blockRewardDataListBuilder_ == null) {
        if (!other.blockRewardDataList_.isEmpty()) {
          if (blockRewardDataList_.isEmpty()) {
            blockRewardDataList_ = other.blockRewardDataList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBlockRewardDataListIsMutable();
            blockRewardDataList_.addAll(other.blockRewardDataList_);
          }
          onChanged();
        }
      } else {
        if (!other.blockRewardDataList_.isEmpty()) {
          if (blockRewardDataListBuilder_.isEmpty()) {
            blockRewardDataListBuilder_.dispose();
            blockRewardDataListBuilder_ = null;
            blockRewardDataList_ = other.blockRewardDataList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            blockRewardDataListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlockRewardDataListFieldBuilder() : null;
          } else {
            blockRewardDataListBuilder_.addAllMessages(other.blockRewardDataList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long blockHeight_ ;
    /**
     * <code>int64 blockHeight = 1;</code>
     * @return The blockHeight.
     */
    @java.lang.Override
    public long getBlockHeight() {
      return blockHeight_;
    }
    /**
     * <code>int64 blockHeight = 1;</code>
     * @param value The blockHeight to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHeight(long value) {
      
      blockHeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blockHeight = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHeight() {
      
      blockHeight_ = 0L;
      onChanged();
      return this;
    }

    private long matureHeight_ ;
    /**
     * <code>int64 matureHeight = 2;</code>
     * @return The matureHeight.
     */
    @java.lang.Override
    public long getMatureHeight() {
      return matureHeight_;
    }
    /**
     * <code>int64 matureHeight = 2;</code>
     * @param value The matureHeight to set.
     * @return This builder for chaining.
     */
    public Builder setMatureHeight(long value) {
      
      matureHeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 matureHeight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatureHeight() {
      
      matureHeight_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto> blockRewardDataList_ =
      java.util.Collections.emptyList();
    private void ensureBlockRewardDataListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        blockRewardDataList_ = new java.util.ArrayList<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto>(blockRewardDataList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder> blockRewardDataListBuilder_;

    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public java.util.List<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto> getBlockRewardDataListList() {
      if (blockRewardDataListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blockRewardDataList_);
      } else {
        return blockRewardDataListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public int getBlockRewardDataListCount() {
      if (blockRewardDataListBuilder_ == null) {
        return blockRewardDataList_.size();
      } else {
        return blockRewardDataListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto getBlockRewardDataList(int index) {
      if (blockRewardDataListBuilder_ == null) {
        return blockRewardDataList_.get(index);
      } else {
        return blockRewardDataListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder setBlockRewardDataList(
        int index, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto value) {
      if (blockRewardDataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.set(index, value);
        onChanged();
      } else {
        blockRewardDataListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder setBlockRewardDataList(
        int index, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder builderForValue) {
      if (blockRewardDataListBuilder_ == null) {
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.set(index, builderForValue.build());
        onChanged();
      } else {
        blockRewardDataListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder addBlockRewardDataList(org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto value) {
      if (blockRewardDataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.add(value);
        onChanged();
      } else {
        blockRewardDataListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder addBlockRewardDataList(
        int index, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto value) {
      if (blockRewardDataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.add(index, value);
        onChanged();
      } else {
        blockRewardDataListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder addBlockRewardDataList(
        org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder builderForValue) {
      if (blockRewardDataListBuilder_ == null) {
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.add(builderForValue.build());
        onChanged();
      } else {
        blockRewardDataListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder addBlockRewardDataList(
        int index, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder builderForValue) {
      if (blockRewardDataListBuilder_ == null) {
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.add(index, builderForValue.build());
        onChanged();
      } else {
        blockRewardDataListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder addAllBlockRewardDataList(
        java.lang.Iterable<? extends org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto> values) {
      if (blockRewardDataListBuilder_ == null) {
        ensureBlockRewardDataListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockRewardDataList_);
        onChanged();
      } else {
        blockRewardDataListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder clearBlockRewardDataList() {
      if (blockRewardDataListBuilder_ == null) {
        blockRewardDataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        blockRewardDataListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public Builder removeBlockRewardDataList(int index) {
      if (blockRewardDataListBuilder_ == null) {
        ensureBlockRewardDataListIsMutable();
        blockRewardDataList_.remove(index);
        onChanged();
      } else {
        blockRewardDataListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder getBlockRewardDataListBuilder(
        int index) {
      return getBlockRewardDataListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder getBlockRewardDataListOrBuilder(
        int index) {
      if (blockRewardDataListBuilder_ == null) {
        return blockRewardDataList_.get(index);  } else {
        return blockRewardDataListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public java.util.List<? extends org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder> 
         getBlockRewardDataListOrBuilderList() {
      if (blockRewardDataListBuilder_ != null) {
        return blockRewardDataListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blockRewardDataList_);
      }
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder addBlockRewardDataListBuilder() {
      return getBlockRewardDataListFieldBuilder().addBuilder(
          org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.getDefaultInstance());
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder addBlockRewardDataListBuilder(
        int index) {
      return getBlockRewardDataListFieldBuilder().addBuilder(
          index, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.getDefaultInstance());
    }
    /**
     * <code>repeated .org.qsn.protobuf.BlockRewardDataDto blockRewardDataList = 3;</code>
     */
    public java.util.List<org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder> 
         getBlockRewardDataListBuilderList() {
      return getBlockRewardDataListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder> 
        getBlockRewardDataListFieldBuilder() {
      if (blockRewardDataListBuilder_ == null) {
        blockRewardDataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDto.Builder, org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDataDtoOrBuilder>(
                blockRewardDataList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        blockRewardDataList_ = null;
      }
      return blockRewardDataListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.BlockRewardDto)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.BlockRewardDto)
  private static final org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockRewardDto>
      PARSER = new com.google.protobuf.AbstractParser<BlockRewardDto>() {
    @java.lang.Override
    public BlockRewardDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BlockRewardDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BlockRewardDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockRewardDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.customized.BlockRewardDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

