// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/customized/DeployContractTxDataDto.proto

package org.qsn.api.rpc.grpc.proto.entity.customized;

/**
 * Protobuf type {@code org.qsn.protobuf.DeployContractTxDataDto}
 */
public final class DeployContractTxDataDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.DeployContractTxDataDto)
    DeployContractTxDataDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeployContractTxDataDto.newBuilder() to construct.
  private DeployContractTxDataDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeployContractTxDataDto() {
    contractCode_ = com.google.protobuf.ByteString.EMPTY;
    contractName_ = "";
    contractClassName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeployContractTxDataDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeployContractTxDataDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            contractCode_ = input.readBytes();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            contractName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            contractClassName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDtoOuterClass.internal_static_org_qsn_protobuf_DeployContractTxDataDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDtoOuterClass.internal_static_org_qsn_protobuf_DeployContractTxDataDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.class, org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.Builder.class);
  }

  public static final int CONTRACTCODE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString contractCode_;
  /**
   * <code>bytes contractCode = 1;</code>
   * @return The contractCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContractCode() {
    return contractCode_;
  }

  public static final int CONTRACTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object contractName_;
  /**
   * <code>string contractName = 2;</code>
   * @return The contractName.
   */
  @java.lang.Override
  public java.lang.String getContractName() {
    java.lang.Object ref = contractName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractName_ = s;
      return s;
    }
  }
  /**
   * <code>string contractName = 2;</code>
   * @return The bytes for contractName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractNameBytes() {
    java.lang.Object ref = contractName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACTCLASSNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object contractClassName_;
  /**
   * <code>string contractClassName = 3;</code>
   * @return The contractClassName.
   */
  @java.lang.Override
  public java.lang.String getContractClassName() {
    java.lang.Object ref = contractClassName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractClassName_ = s;
      return s;
    }
  }
  /**
   * <code>string contractClassName = 3;</code>
   * @return The bytes for contractClassName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractClassNameBytes() {
    java.lang.Object ref = contractClassName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractClassName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!contractCode_.isEmpty()) {
      output.writeBytes(1, contractCode_);
    }
    if (!getContractNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contractName_);
    }
    if (!getContractClassNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contractClassName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!contractCode_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, contractCode_);
    }
    if (!getContractNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contractName_);
    }
    if (!getContractClassNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contractClassName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto other = (org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto) obj;

    if (!getContractCode()
        .equals(other.getContractCode())) return false;
    if (!getContractName()
        .equals(other.getContractName())) return false;
    if (!getContractClassName()
        .equals(other.getContractClassName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getContractCode().hashCode();
    hash = (37 * hash) + CONTRACTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getContractName().hashCode();
    hash = (37 * hash) + CONTRACTCLASSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getContractClassName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.DeployContractTxDataDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.DeployContractTxDataDto)
      org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDtoOuterClass.internal_static_org_qsn_protobuf_DeployContractTxDataDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDtoOuterClass.internal_static_org_qsn_protobuf_DeployContractTxDataDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.class, org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      contractCode_ = com.google.protobuf.ByteString.EMPTY;

      contractName_ = "";

      contractClassName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDtoOuterClass.internal_static_org_qsn_protobuf_DeployContractTxDataDto_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto build() {
      org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto result = new org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto(this);
      result.contractCode_ = contractCode_;
      result.contractName_ = contractName_;
      result.contractClassName_ = contractClassName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto.getDefaultInstance()) return this;
      if (other.getContractCode() != com.google.protobuf.ByteString.EMPTY) {
        setContractCode(other.getContractCode());
      }
      if (!other.getContractName().isEmpty()) {
        contractName_ = other.contractName_;
        onChanged();
      }
      if (!other.getContractClassName().isEmpty()) {
        contractClassName_ = other.contractClassName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString contractCode_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes contractCode = 1;</code>
     * @return The contractCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContractCode() {
      return contractCode_;
    }
    /**
     * <code>bytes contractCode = 1;</code>
     * @param value The contractCode to set.
     * @return This builder for chaining.
     */
    public Builder setContractCode(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes contractCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractCode() {
      
      contractCode_ = getDefaultInstance().getContractCode();
      onChanged();
      return this;
    }

    private java.lang.Object contractName_ = "";
    /**
     * <code>string contractName = 2;</code>
     * @return The contractName.
     */
    public java.lang.String getContractName() {
      java.lang.Object ref = contractName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contractName = 2;</code>
     * @return The bytes for contractName.
     */
    public com.google.protobuf.ByteString
        getContractNameBytes() {
      java.lang.Object ref = contractName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contractName = 2;</code>
     * @param value The contractName to set.
     * @return This builder for chaining.
     */
    public Builder setContractName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contractName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractName() {
      
      contractName_ = getDefaultInstance().getContractName();
      onChanged();
      return this;
    }
    /**
     * <code>string contractName = 2;</code>
     * @param value The bytes for contractName to set.
     * @return This builder for chaining.
     */
    public Builder setContractNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contractClassName_ = "";
    /**
     * <code>string contractClassName = 3;</code>
     * @return The contractClassName.
     */
    public java.lang.String getContractClassName() {
      java.lang.Object ref = contractClassName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractClassName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contractClassName = 3;</code>
     * @return The bytes for contractClassName.
     */
    public com.google.protobuf.ByteString
        getContractClassNameBytes() {
      java.lang.Object ref = contractClassName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractClassName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contractClassName = 3;</code>
     * @param value The contractClassName to set.
     * @return This builder for chaining.
     */
    public Builder setContractClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractClassName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contractClassName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractClassName() {
      
      contractClassName_ = getDefaultInstance().getContractClassName();
      onChanged();
      return this;
    }
    /**
     * <code>string contractClassName = 3;</code>
     * @param value The bytes for contractClassName to set.
     * @return This builder for chaining.
     */
    public Builder setContractClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractClassName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.DeployContractTxDataDto)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.DeployContractTxDataDto)
  private static final org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeployContractTxDataDto>
      PARSER = new com.google.protobuf.AbstractParser<DeployContractTxDataDto>() {
    @java.lang.Override
    public DeployContractTxDataDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeployContractTxDataDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeployContractTxDataDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeployContractTxDataDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.customized.DeployContractTxDataDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

