// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/customized/SampleTxDataDto.proto

package org.qsn.api.rpc.grpc.proto.entity.customized;

public final class SampleTxDataDtoOuterClass {
  private SampleTxDataDtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_qsn_protobuf_SampleTxDataDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_qsn_protobuf_SampleTxDataDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+qsn/entity/customized/SampleTxDataDto." +
      "proto\022\020org.qsn.protobuf\032 qsn/entity/comm" +
      "on/BInteger.proto\"\230\001\n\017SampleTxDataDto\022\014\n" +
      "\004from\030\001 \001(\014\022\n\n\002to\030\002 \001(\014\022)\n\005value\030\003 \001(\0132\032" +
      ".org.qsn.protobuf.BInteger\022\024\n\014stakeAddre" +
      "ss\030\004 \001(\t\022\020\n\010nodeName\030\005 \001(\t\022\030\n\020validatorA" +
      "ddress\030\006 \001(\tB0\n,org.qsn.api.rpc.grpc.pro" +
      "to.entity.customizedP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOuterClass.getDescriptor(),
        });
    internal_static_org_qsn_protobuf_SampleTxDataDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_qsn_protobuf_SampleTxDataDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_qsn_protobuf_SampleTxDataDto_descriptor,
        new java.lang.String[] { "From", "To", "Value", "StakeAddress", "NodeName", "ValidatorAddress", });
    org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
