// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/customized/ValidatorTxDataDto.proto

package org.qsn.api.rpc.grpc.proto.entity.customized;

/**
 * Protobuf type {@code org.qsn.protobuf.ValidatorTxDataDto}
 */
public final class ValidatorTxDataDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.ValidatorTxDataDto)
    ValidatorTxDataDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidatorTxDataDto.newBuilder() to construct.
  private ValidatorTxDataDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidatorTxDataDto() {
    validatorAddress_ = com.google.protobuf.ByteString.EMPTY;
    validatorPubKey_ = com.google.protobuf.ByteString.EMPTY;
    delegationAddress_ = com.google.protobuf.ByteString.EMPTY;
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidatorTxDataDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValidatorTxDataDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            validatorAddress_ = input.readBytes();
            break;
          }
          case 18: {

            validatorPubKey_ = input.readBytes();
            break;
          }
          case 26: {

            delegationAddress_ = input.readBytes();
            break;
          }
          case 34: {
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.BInteger.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDtoOuterClass.internal_static_org_qsn_protobuf_ValidatorTxDataDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDtoOuterClass.internal_static_org_qsn_protobuf_ValidatorTxDataDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.class, org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.Builder.class);
  }

  public static final int VALIDATORADDRESS_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString validatorAddress_;
  /**
   * <code>bytes validatorAddress = 1;</code>
   * @return The validatorAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValidatorAddress() {
    return validatorAddress_;
  }

  public static final int VALIDATORPUBKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString validatorPubKey_;
  /**
   * <code>bytes validatorPubKey = 2;</code>
   * @return The validatorPubKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValidatorPubKey() {
    return validatorPubKey_;
  }

  public static final int DELEGATIONADDRESS_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString delegationAddress_;
  /**
   * <code>bytes delegationAddress = 3;</code>
   * @return The delegationAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDelegationAddress() {
    return delegationAddress_;
  }

  public static final int VALUE_FIELD_NUMBER = 4;
  private org.qsn.api.rpc.grpc.proto.entity.common.BInteger value_;
  /**
   * <code>.org.qsn.protobuf.BInteger value = 4;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.BInteger value = 4;</code>
   * @return The value.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BInteger getValue() {
    return value_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : value_;
  }
  /**
   * <code>.org.qsn.protobuf.BInteger value = 4;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getValueOrBuilder() {
    return getValue();
  }

  public static final int NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!validatorAddress_.isEmpty()) {
      output.writeBytes(1, validatorAddress_);
    }
    if (!validatorPubKey_.isEmpty()) {
      output.writeBytes(2, validatorPubKey_);
    }
    if (!delegationAddress_.isEmpty()) {
      output.writeBytes(3, delegationAddress_);
    }
    if (value_ != null) {
      output.writeMessage(4, getValue());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!validatorAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, validatorAddress_);
    }
    if (!validatorPubKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, validatorPubKey_);
    }
    if (!delegationAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, delegationAddress_);
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getValue());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto other = (org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto) obj;

    if (!getValidatorAddress()
        .equals(other.getValidatorAddress())) return false;
    if (!getValidatorPubKey()
        .equals(other.getValidatorPubKey())) return false;
    if (!getDelegationAddress()
        .equals(other.getDelegationAddress())) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALIDATORADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getValidatorAddress().hashCode();
    hash = (37 * hash) + VALIDATORPUBKEY_FIELD_NUMBER;
    hash = (53 * hash) + getValidatorPubKey().hashCode();
    hash = (37 * hash) + DELEGATIONADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDelegationAddress().hashCode();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.ValidatorTxDataDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.ValidatorTxDataDto)
      org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDtoOuterClass.internal_static_org_qsn_protobuf_ValidatorTxDataDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDtoOuterClass.internal_static_org_qsn_protobuf_ValidatorTxDataDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.class, org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      validatorAddress_ = com.google.protobuf.ByteString.EMPTY;

      validatorPubKey_ = com.google.protobuf.ByteString.EMPTY;

      delegationAddress_ = com.google.protobuf.ByteString.EMPTY;

      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDtoOuterClass.internal_static_org_qsn_protobuf_ValidatorTxDataDto_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto build() {
      org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto result = new org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto(this);
      result.validatorAddress_ = validatorAddress_;
      result.validatorPubKey_ = validatorPubKey_;
      result.delegationAddress_ = delegationAddress_;
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto.getDefaultInstance()) return this;
      if (other.getValidatorAddress() != com.google.protobuf.ByteString.EMPTY) {
        setValidatorAddress(other.getValidatorAddress());
      }
      if (other.getValidatorPubKey() != com.google.protobuf.ByteString.EMPTY) {
        setValidatorPubKey(other.getValidatorPubKey());
      }
      if (other.getDelegationAddress() != com.google.protobuf.ByteString.EMPTY) {
        setDelegationAddress(other.getDelegationAddress());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString validatorAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes validatorAddress = 1;</code>
     * @return The validatorAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValidatorAddress() {
      return validatorAddress_;
    }
    /**
     * <code>bytes validatorAddress = 1;</code>
     * @param value The validatorAddress to set.
     * @return This builder for chaining.
     */
    public Builder setValidatorAddress(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      validatorAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes validatorAddress = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidatorAddress() {
      
      validatorAddress_ = getDefaultInstance().getValidatorAddress();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString validatorPubKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes validatorPubKey = 2;</code>
     * @return The validatorPubKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValidatorPubKey() {
      return validatorPubKey_;
    }
    /**
     * <code>bytes validatorPubKey = 2;</code>
     * @param value The validatorPubKey to set.
     * @return This builder for chaining.
     */
    public Builder setValidatorPubKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      validatorPubKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes validatorPubKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidatorPubKey() {
      
      validatorPubKey_ = getDefaultInstance().getValidatorPubKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString delegationAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes delegationAddress = 3;</code>
     * @return The delegationAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDelegationAddress() {
      return delegationAddress_;
    }
    /**
     * <code>bytes delegationAddress = 3;</code>
     * @param value The delegationAddress to set.
     * @return This builder for chaining.
     */
    public Builder setDelegationAddress(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      delegationAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes delegationAddress = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelegationAddress() {
      
      delegationAddress_ = getDefaultInstance().getDelegationAddress();
      onChanged();
      return this;
    }

    private org.qsn.api.rpc.grpc.proto.entity.common.BInteger value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder> valueBuilder_;
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     * @return The value.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BInteger getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    public Builder setValue(org.qsn.api.rpc.grpc.proto.entity.common.BInteger value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    public Builder setValue(
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    public Builder mergeValue(org.qsn.api.rpc.grpc.proto.entity.common.BInteger value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.BInteger value = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.BInteger, org.qsn.api.rpc.grpc.proto.entity.common.BInteger.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.ValidatorTxDataDto)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.ValidatorTxDataDto)
  private static final org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidatorTxDataDto>
      PARSER = new com.google.protobuf.AbstractParser<ValidatorTxDataDto>() {
    @java.lang.Override
    public ValidatorTxDataDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValidatorTxDataDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValidatorTxDataDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidatorTxDataDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.customized.ValidatorTxDataDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

