// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/common/account/Account.proto

package org.qsn.api.rpc.grpc.proto.entity.common.account;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_qsn_protobuf_AccountDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_qsn_protobuf_AccountDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'qsn/entity/common/account/Account.prot" +
      "o\022\020org.qsn.protobuf\032 qsn/entity/common/B" +
      "Integer.proto\"d\n\nAccountDto\022+\n\007balance\030\001" +
      " \001(\0132\032.org.qsn.protobuf.BInteger\022)\n\005nonc" +
      "e\030\002 \001(\0132\032.org.qsn.protobuf.BIntegerB4\n0o" +
      "rg.qsn.api.rpc.grpc.proto.entity.common." +
      "accountP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOuterClass.getDescriptor(),
        });
    internal_static_org_qsn_protobuf_AccountDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_qsn_protobuf_AccountDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_qsn_protobuf_AccountDto_descriptor,
        new java.lang.String[] { "Balance", "Nonce", });
    org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
