// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/request/TransactionRequests.proto

package org.qsn.api.rpc.grpc.proto.entity.request;

public interface CreateRawDeployContractTxRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.qsn.protobuf.CreateRawDeployContractTxRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  boolean hasBaseRequest();
  /**
   * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
   * @return The baseRequest.
   */
  org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest getBaseRequest();
  /**
   * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
   */
  org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOrBuilder getBaseRequestOrBuilder();

  /**
   * <code>bytes contractCode = 2;</code>
   * @return The contractCode.
   */
  com.google.protobuf.ByteString getContractCode();

  /**
   * <code>string contractName = 3;</code>
   * @return The contractName.
   */
  java.lang.String getContractName();
  /**
   * <code>string contractName = 3;</code>
   * @return The bytes for contractName.
   */
  com.google.protobuf.ByteString
      getContractNameBytes();

  /**
   * <code>string contractClassName = 4;</code>
   * @return The contractClassName.
   */
  java.lang.String getContractClassName();
  /**
   * <code>string contractClassName = 4;</code>
   * @return The bytes for contractClassName.
   */
  com.google.protobuf.ByteString
      getContractClassNameBytes();
}
