// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/request/SendTransactionRequest.proto

package org.qsn.api.rpc.grpc.proto.entity.request;

public final class SendTransactionRequestOuterClass {
  private SendTransactionRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_qsn_protobuf_SendTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_qsn_protobuf_SendTransactionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/qsn/entity/request/SendTransactionRequ" +
      "est.proto\022\020org.qsn.protobuf\032#qsn/entity/" +
      "common/BaseRequest.proto\0322qsn/entity/com" +
      "mon/transaction/TransactionDto.proto\"\206\001\n" +
      "\026SendTransactionRequest\0222\n\013baseRequest\030\001" +
      " \001(\0132\035.org.qsn.protobuf.BaseRequest\0228\n\016t" +
      "ransactionDto\030\002 \001(\0132 .org.qsn.protobuf.T" +
      "ransactionDtoB-\n)org.qsn.api.rpc.grpc.pr" +
      "oto.entity.requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOuterClass.getDescriptor(),
          org.qsn.api.rpc.grpc.proto.entity.common.transaction.TransactionDtoOuterClass.getDescriptor(),
        });
    internal_static_org_qsn_protobuf_SendTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_qsn_protobuf_SendTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_qsn_protobuf_SendTransactionRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "TransactionDto", });
    org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOuterClass.getDescriptor();
    org.qsn.api.rpc.grpc.proto.entity.common.transaction.TransactionDtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
