// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/request/SmartContractRequests.proto

package org.qsn.api.rpc.grpc.proto.entity.request;

/**
 * Protobuf type {@code org.qsn.protobuf.SmartContractViewOnlyRequest}
 */
public final class SmartContractViewOnlyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.SmartContractViewOnlyRequest)
    SmartContractViewOnlyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SmartContractViewOnlyRequest.newBuilder() to construct.
  private SmartContractViewOnlyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SmartContractViewOnlyRequest() {
    contractName_ = "";
    contractAction_ = "";
    contractArguments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SmartContractViewOnlyRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SmartContractViewOnlyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.Builder subBuilder = null;
            if (baseRequest_ != null) {
              subBuilder = baseRequest_.toBuilder();
            }
            baseRequest_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseRequest_);
              baseRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            contractName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            contractAction_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              contractArguments_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            contractArguments_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        contractArguments_ = java.util.Collections.unmodifiableList(contractArguments_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.request.SmartContractRequests.internal_static_org_qsn_protobuf_SmartContractViewOnlyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.request.SmartContractRequests.internal_static_org_qsn_protobuf_SmartContractViewOnlyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.class, org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.Builder.class);
  }

  public static final int BASEREQUEST_FIELD_NUMBER = 1;
  private org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest baseRequest_;
  /**
   * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  @java.lang.Override
  public boolean hasBaseRequest() {
    return baseRequest_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
   * @return The baseRequest.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest getBaseRequest() {
    return baseRequest_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }
  /**
   * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
    return getBaseRequest();
  }

  public static final int CONTRACTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object contractName_;
  /**
   * <code>string contractName = 2;</code>
   * @return The contractName.
   */
  @java.lang.Override
  public java.lang.String getContractName() {
    java.lang.Object ref = contractName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractName_ = s;
      return s;
    }
  }
  /**
   * <code>string contractName = 2;</code>
   * @return The bytes for contractName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractNameBytes() {
    java.lang.Object ref = contractName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACTACTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object contractAction_;
  /**
   * <code>string contractAction = 3;</code>
   * @return The contractAction.
   */
  @java.lang.Override
  public java.lang.String getContractAction() {
    java.lang.Object ref = contractAction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractAction_ = s;
      return s;
    }
  }
  /**
   * <code>string contractAction = 3;</code>
   * @return The bytes for contractAction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractActionBytes() {
    java.lang.Object ref = contractAction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractAction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACTARGUMENTS_FIELD_NUMBER = 4;
  private java.util.List<com.google.protobuf.ByteString> contractArguments_;
  /**
   * <code>repeated bytes contractArguments = 4;</code>
   * @return A list containing the contractArguments.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getContractArgumentsList() {
    return contractArguments_;
  }
  /**
   * <code>repeated bytes contractArguments = 4;</code>
   * @return The count of contractArguments.
   */
  public int getContractArgumentsCount() {
    return contractArguments_.size();
  }
  /**
   * <code>repeated bytes contractArguments = 4;</code>
   * @param index The index of the element to return.
   * @return The contractArguments at the given index.
   */
  public com.google.protobuf.ByteString getContractArguments(int index) {
    return contractArguments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseRequest_ != null) {
      output.writeMessage(1, getBaseRequest());
    }
    if (!getContractNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contractName_);
    }
    if (!getContractActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contractAction_);
    }
    for (int i = 0; i < contractArguments_.size(); i++) {
      output.writeBytes(4, contractArguments_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseRequest());
    }
    if (!getContractNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contractName_);
    }
    if (!getContractActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contractAction_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < contractArguments_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(contractArguments_.get(i));
      }
      size += dataSize;
      size += 1 * getContractArgumentsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest other = (org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest) obj;

    if (hasBaseRequest() != other.hasBaseRequest()) return false;
    if (hasBaseRequest()) {
      if (!getBaseRequest()
          .equals(other.getBaseRequest())) return false;
    }
    if (!getContractName()
        .equals(other.getContractName())) return false;
    if (!getContractAction()
        .equals(other.getContractAction())) return false;
    if (!getContractArgumentsList()
        .equals(other.getContractArgumentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseRequest()) {
      hash = (37 * hash) + BASEREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getBaseRequest().hashCode();
    }
    hash = (37 * hash) + CONTRACTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getContractName().hashCode();
    hash = (37 * hash) + CONTRACTACTION_FIELD_NUMBER;
    hash = (53 * hash) + getContractAction().hashCode();
    if (getContractArgumentsCount() > 0) {
      hash = (37 * hash) + CONTRACTARGUMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContractArgumentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.SmartContractViewOnlyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.SmartContractViewOnlyRequest)
      org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.request.SmartContractRequests.internal_static_org_qsn_protobuf_SmartContractViewOnlyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.request.SmartContractRequests.internal_static_org_qsn_protobuf_SmartContractViewOnlyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.class, org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (baseRequestBuilder_ == null) {
        baseRequest_ = null;
      } else {
        baseRequest_ = null;
        baseRequestBuilder_ = null;
      }
      contractName_ = "";

      contractAction_ = "";

      contractArguments_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.request.SmartContractRequests.internal_static_org_qsn_protobuf_SmartContractViewOnlyRequest_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest build() {
      org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest result = new org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest(this);
      int from_bitField0_ = bitField0_;
      if (baseRequestBuilder_ == null) {
        result.baseRequest_ = baseRequest_;
      } else {
        result.baseRequest_ = baseRequestBuilder_.build();
      }
      result.contractName_ = contractName_;
      result.contractAction_ = contractAction_;
      if (((bitField0_ & 0x00000001) != 0)) {
        contractArguments_ = java.util.Collections.unmodifiableList(contractArguments_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.contractArguments_ = contractArguments_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest.getDefaultInstance()) return this;
      if (other.hasBaseRequest()) {
        mergeBaseRequest(other.getBaseRequest());
      }
      if (!other.getContractName().isEmpty()) {
        contractName_ = other.contractName_;
        onChanged();
      }
      if (!other.getContractAction().isEmpty()) {
        contractAction_ = other.contractAction_;
        onChanged();
      }
      if (!other.contractArguments_.isEmpty()) {
        if (contractArguments_.isEmpty()) {
          contractArguments_ = other.contractArguments_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureContractArgumentsIsMutable();
          contractArguments_.addAll(other.contractArguments_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest baseRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest, org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOrBuilder> baseRequestBuilder_;
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     * @return Whether the baseRequest field is set.
     */
    public boolean hasBaseRequest() {
      return baseRequestBuilder_ != null || baseRequest_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     * @return The baseRequest.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest getBaseRequest() {
      if (baseRequestBuilder_ == null) {
        return baseRequest_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.getDefaultInstance() : baseRequest_;
      } else {
        return baseRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    public Builder setBaseRequest(org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseRequest_ = value;
        onChanged();
      } else {
        baseRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    public Builder setBaseRequest(
        org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.Builder builderForValue) {
      if (baseRequestBuilder_ == null) {
        baseRequest_ = builderForValue.build();
        onChanged();
      } else {
        baseRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    public Builder mergeBaseRequest(org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (baseRequest_ != null) {
          baseRequest_ =
            org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.newBuilder(baseRequest_).mergeFrom(value).buildPartial();
        } else {
          baseRequest_ = value;
        }
        onChanged();
      } else {
        baseRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    public Builder clearBaseRequest() {
      if (baseRequestBuilder_ == null) {
        baseRequest_ = null;
        onChanged();
      } else {
        baseRequest_ = null;
        baseRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.Builder getBaseRequestBuilder() {
      
      onChanged();
      return getBaseRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      if (baseRequestBuilder_ != null) {
        return baseRequestBuilder_.getMessageOrBuilder();
      } else {
        return baseRequest_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.getDefaultInstance() : baseRequest_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.BaseRequest baseRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest, org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOrBuilder> 
        getBaseRequestFieldBuilder() {
      if (baseRequestBuilder_ == null) {
        baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest, org.qsn.api.rpc.grpc.proto.entity.common.BaseRequest.Builder, org.qsn.api.rpc.grpc.proto.entity.common.BaseRequestOrBuilder>(
                getBaseRequest(),
                getParentForChildren(),
                isClean());
        baseRequest_ = null;
      }
      return baseRequestBuilder_;
    }

    private java.lang.Object contractName_ = "";
    /**
     * <code>string contractName = 2;</code>
     * @return The contractName.
     */
    public java.lang.String getContractName() {
      java.lang.Object ref = contractName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contractName = 2;</code>
     * @return The bytes for contractName.
     */
    public com.google.protobuf.ByteString
        getContractNameBytes() {
      java.lang.Object ref = contractName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contractName = 2;</code>
     * @param value The contractName to set.
     * @return This builder for chaining.
     */
    public Builder setContractName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contractName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractName() {
      
      contractName_ = getDefaultInstance().getContractName();
      onChanged();
      return this;
    }
    /**
     * <code>string contractName = 2;</code>
     * @param value The bytes for contractName to set.
     * @return This builder for chaining.
     */
    public Builder setContractNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contractAction_ = "";
    /**
     * <code>string contractAction = 3;</code>
     * @return The contractAction.
     */
    public java.lang.String getContractAction() {
      java.lang.Object ref = contractAction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractAction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contractAction = 3;</code>
     * @return The bytes for contractAction.
     */
    public com.google.protobuf.ByteString
        getContractActionBytes() {
      java.lang.Object ref = contractAction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contractAction = 3;</code>
     * @param value The contractAction to set.
     * @return This builder for chaining.
     */
    public Builder setContractAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractAction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contractAction = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractAction() {
      
      contractAction_ = getDefaultInstance().getContractAction();
      onChanged();
      return this;
    }
    /**
     * <code>string contractAction = 3;</code>
     * @param value The bytes for contractAction to set.
     * @return This builder for chaining.
     */
    public Builder setContractActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractAction_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> contractArguments_ = java.util.Collections.emptyList();
    private void ensureContractArgumentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        contractArguments_ = new java.util.ArrayList<com.google.protobuf.ByteString>(contractArguments_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @return A list containing the contractArguments.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getContractArgumentsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(contractArguments_) : contractArguments_;
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @return The count of contractArguments.
     */
    public int getContractArgumentsCount() {
      return contractArguments_.size();
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @param index The index of the element to return.
     * @return The contractArguments at the given index.
     */
    public com.google.protobuf.ByteString getContractArguments(int index) {
      return contractArguments_.get(index);
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @param index The index to set the value at.
     * @param value The contractArguments to set.
     * @return This builder for chaining.
     */
    public Builder setContractArguments(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContractArgumentsIsMutable();
      contractArguments_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @param value The contractArguments to add.
     * @return This builder for chaining.
     */
    public Builder addContractArguments(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContractArgumentsIsMutable();
      contractArguments_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @param values The contractArguments to add.
     * @return This builder for chaining.
     */
    public Builder addAllContractArguments(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureContractArgumentsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, contractArguments_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes contractArguments = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractArguments() {
      contractArguments_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.SmartContractViewOnlyRequest)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.SmartContractViewOnlyRequest)
  private static final org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SmartContractViewOnlyRequest>
      PARSER = new com.google.protobuf.AbstractParser<SmartContractViewOnlyRequest>() {
    @java.lang.Override
    public SmartContractViewOnlyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SmartContractViewOnlyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SmartContractViewOnlyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SmartContractViewOnlyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.request.SmartContractViewOnlyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

