# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qsn/entity/common/transaction/TransactionDataDto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qsn.entity.common import BInteger_pb2 as qsn_dot_entity_dot_common_dot_BInteger__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qsn/entity/common/transaction/TransactionDataDto.proto',
  package='org.qsn.protobuf',
  syntax='proto3',
  serialized_options=b'\n4org.qsn.api.rpc.grpc.proto.entity.common.transactionP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6qsn/entity/common/transaction/TransactionDataDto.proto\x12\x10org.qsn.protobuf\x1a qsn/entity/common/BInteger.proto\x1a\x19google/protobuf/any.proto\"s\n\x12TransactionDataDto\x12\x0e\n\x06sender\x18\x01 \x01(\x0c\x12)\n\x05nonce\x18\x02 \x01(\x0b\x32\x1a.org.qsn.protobuf.BInteger\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB8\n4org.qsn.api.rpc.grpc.proto.entity.common.transactionP\x01\x62\x06proto3'
  ,
  dependencies=[qsn_dot_entity_dot_common_dot_BInteger__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_TRANSACTIONDATADTO = _descriptor.Descriptor(
  name='TransactionDataDto',
  full_name='org.qsn.protobuf.TransactionDataDto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='org.qsn.protobuf.TransactionDataDto.sender', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='org.qsn.protobuf.TransactionDataDto.nonce', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='org.qsn.protobuf.TransactionDataDto.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=252,
)

_TRANSACTIONDATADTO.fields_by_name['nonce'].message_type = qsn_dot_entity_dot_common_dot_BInteger__pb2._BINTEGER
_TRANSACTIONDATADTO.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['TransactionDataDto'] = _TRANSACTIONDATADTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionDataDto = _reflection.GeneratedProtocolMessageType('TransactionDataDto', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONDATADTO,
  '__module__' : 'qsn.entity.common.transaction.TransactionDataDto_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.TransactionDataDto)
  })
_sym_db.RegisterMessage(TransactionDataDto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
