# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qsn/entity/common/transaction/TransactionReceiptDto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qsn/entity/common/transaction/TransactionReceiptDto.proto',
  package='org.qsn.protobuf',
  syntax='proto3',
  serialized_options=b'\n4org.qsn.api.rpc.grpc.proto.entity.common.transactionP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9qsn/entity/common/transaction/TransactionReceiptDto.proto\x12\x10org.qsn.protobuf\"\x98\x02\n\x15TransactionReceiptDto\x12\x11\n\tblockHash\x18\x01 \x01(\x0c\x12\x13\n\x0b\x62lockHeight\x18\x02 \x01(\x03\x12\x17\n\x0ftransactionHash\x18\x03 \x01(\x0c\x12\x18\n\x10transactionIndex\x18\x04 \x01(\x05\x12\x0e\n\x06sender\x18\x05 \x01(\x0c\x12\x0f\n\x07\x66\x65\x65Used\x18\x06 \x01(\x03\x12\x0e\n\x06status\x18\x07 \x01(\x05\x12\x14\n\x0c\x63ontractName\x18\x08 \x01(\t\x12\x16\n\x0e\x63ontractAction\x18\t \x01(\t\x12\x16\n\x0e\x63ontractResult\x18\n \x01(\x0c\x12\x1f\n\x17\x64\x65ployedContractAddress\x18\x0b \x01(\x0c\x12\x0c\n\x04logs\x18\x0c \x03(\tB8\n4org.qsn.api.rpc.grpc.proto.entity.common.transactionP\x01\x62\x06proto3'
)




_TRANSACTIONRECEIPTDTO = _descriptor.Descriptor(
  name='TransactionReceiptDto',
  full_name='org.qsn.protobuf.TransactionReceiptDto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockHash', full_name='org.qsn.protobuf.TransactionReceiptDto.blockHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blockHeight', full_name='org.qsn.protobuf.TransactionReceiptDto.blockHeight', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionHash', full_name='org.qsn.protobuf.TransactionReceiptDto.transactionHash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionIndex', full_name='org.qsn.protobuf.TransactionReceiptDto.transactionIndex', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='org.qsn.protobuf.TransactionReceiptDto.sender', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feeUsed', full_name='org.qsn.protobuf.TransactionReceiptDto.feeUsed', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='org.qsn.protobuf.TransactionReceiptDto.status', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractName', full_name='org.qsn.protobuf.TransactionReceiptDto.contractName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractAction', full_name='org.qsn.protobuf.TransactionReceiptDto.contractAction', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractResult', full_name='org.qsn.protobuf.TransactionReceiptDto.contractResult', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deployedContractAddress', full_name='org.qsn.protobuf.TransactionReceiptDto.deployedContractAddress', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logs', full_name='org.qsn.protobuf.TransactionReceiptDto.logs', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=360,
)

DESCRIPTOR.message_types_by_name['TransactionReceiptDto'] = _TRANSACTIONRECEIPTDTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionReceiptDto = _reflection.GeneratedProtocolMessageType('TransactionReceiptDto', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONRECEIPTDTO,
  '__module__' : 'qsn.entity.common.transaction.TransactionReceiptDto_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.TransactionReceiptDto)
  })
_sym_db.RegisterMessage(TransactionReceiptDto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
