# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qsn/entity/response/TransactionResponses.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qsn.entity.common import Result_pb2 as qsn_dot_entity_dot_common_dot_Result__pb2
from qsn.entity.common.transaction import TransactionReceiptDto_pb2 as qsn_dot_entity_dot_common_dot_transaction_dot_TransactionReceiptDto__pb2
from qsn.entity.common.transaction import TransactionDto_pb2 as qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qsn/entity/response/TransactionResponses.proto',
  package='org.qsn.protobuf',
  syntax='proto3',
  serialized_options=b'\n*org.qsn.api.rpc.grpc.proto.entity.responseP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.qsn/entity/response/TransactionResponses.proto\x12\x10org.qsn.protobuf\x1a\x1eqsn/entity/common/Result.proto\x1a\x39qsn/entity/common/transaction/TransactionReceiptDto.proto\x1a\x32qsn/entity/common/transaction/TransactionDto.proto\"C\n\x17SendTransactionResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\"\x8e\x01\n\x1dGetTransactionReceiptResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\x12\x43\n\x12transactionReceipt\x18\x02 \x01(\x0b\x32\'.org.qsn.protobuf.TransactionReceiptDto\"y\n\x16GetTransactionResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\x12\x35\n\x0btransaction\x18\x02 \x01(\x0b\x32 .org.qsn.protobuf.TransactionDto\"~\n\x1b\x43reateRawTransferTxResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\x12\x35\n\x0btransaction\x18\x02 \x01(\x0b\x32 .org.qsn.protobuf.TransactionDto\"\x84\x01\n!CreateRawDeployContractTxResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\x12\x35\n\x0btransaction\x18\x02 \x01(\x0b\x32 .org.qsn.protobuf.TransactionDto\"\x7f\n\x1c\x43reateRawValidatorTxResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\x12\x35\n\x0btransaction\x18\x02 \x01(\x0b\x32 .org.qsn.protobuf.TransactionDto\"~\n\x1b\x43reateRawWithdrawTxResponse\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.org.qsn.protobuf.Result\x12\x35\n\x0btransaction\x18\x02 \x01(\x0b\x32 .org.qsn.protobuf.TransactionDtoB.\n*org.qsn.api.rpc.grpc.proto.entity.responseP\x01\x62\x06proto3'
  ,
  dependencies=[qsn_dot_entity_dot_common_dot_Result__pb2.DESCRIPTOR,qsn_dot_entity_dot_common_dot_transaction_dot_TransactionReceiptDto__pb2.DESCRIPTOR,qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2.DESCRIPTOR,])




_SENDTRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='SendTransactionResponse',
  full_name='org.qsn.protobuf.SendTransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.SendTransactionResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=278,
)


_GETTRANSACTIONRECEIPTRESPONSE = _descriptor.Descriptor(
  name='GetTransactionReceiptResponse',
  full_name='org.qsn.protobuf.GetTransactionReceiptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.GetTransactionReceiptResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionReceipt', full_name='org.qsn.protobuf.GetTransactionReceiptResponse.transactionReceipt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=423,
)


_GETTRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='GetTransactionResponse',
  full_name='org.qsn.protobuf.GetTransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.GetTransactionResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='org.qsn.protobuf.GetTransactionResponse.transaction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=546,
)


_CREATERAWTRANSFERTXRESPONSE = _descriptor.Descriptor(
  name='CreateRawTransferTxResponse',
  full_name='org.qsn.protobuf.CreateRawTransferTxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.CreateRawTransferTxResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='org.qsn.protobuf.CreateRawTransferTxResponse.transaction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=674,
)


_CREATERAWDEPLOYCONTRACTTXRESPONSE = _descriptor.Descriptor(
  name='CreateRawDeployContractTxResponse',
  full_name='org.qsn.protobuf.CreateRawDeployContractTxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.CreateRawDeployContractTxResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='org.qsn.protobuf.CreateRawDeployContractTxResponse.transaction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=809,
)


_CREATERAWVALIDATORTXRESPONSE = _descriptor.Descriptor(
  name='CreateRawValidatorTxResponse',
  full_name='org.qsn.protobuf.CreateRawValidatorTxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.CreateRawValidatorTxResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='org.qsn.protobuf.CreateRawValidatorTxResponse.transaction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=811,
  serialized_end=938,
)


_CREATERAWWITHDRAWTXRESPONSE = _descriptor.Descriptor(
  name='CreateRawWithdrawTxResponse',
  full_name='org.qsn.protobuf.CreateRawWithdrawTxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.qsn.protobuf.CreateRawWithdrawTxResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='org.qsn.protobuf.CreateRawWithdrawTxResponse.transaction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=940,
  serialized_end=1066,
)

_SENDTRANSACTIONRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_GETTRANSACTIONRECEIPTRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_GETTRANSACTIONRECEIPTRESPONSE.fields_by_name['transactionReceipt'].message_type = qsn_dot_entity_dot_common_dot_transaction_dot_TransactionReceiptDto__pb2._TRANSACTIONRECEIPTDTO
_GETTRANSACTIONRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_GETTRANSACTIONRESPONSE.fields_by_name['transaction'].message_type = qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2._TRANSACTIONDTO
_CREATERAWTRANSFERTXRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_CREATERAWTRANSFERTXRESPONSE.fields_by_name['transaction'].message_type = qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2._TRANSACTIONDTO
_CREATERAWDEPLOYCONTRACTTXRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_CREATERAWDEPLOYCONTRACTTXRESPONSE.fields_by_name['transaction'].message_type = qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2._TRANSACTIONDTO
_CREATERAWVALIDATORTXRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_CREATERAWVALIDATORTXRESPONSE.fields_by_name['transaction'].message_type = qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2._TRANSACTIONDTO
_CREATERAWWITHDRAWTXRESPONSE.fields_by_name['result'].message_type = qsn_dot_entity_dot_common_dot_Result__pb2._RESULT
_CREATERAWWITHDRAWTXRESPONSE.fields_by_name['transaction'].message_type = qsn_dot_entity_dot_common_dot_transaction_dot_TransactionDto__pb2._TRANSACTIONDTO
DESCRIPTOR.message_types_by_name['SendTransactionResponse'] = _SENDTRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['GetTransactionReceiptResponse'] = _GETTRANSACTIONRECEIPTRESPONSE
DESCRIPTOR.message_types_by_name['GetTransactionResponse'] = _GETTRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['CreateRawTransferTxResponse'] = _CREATERAWTRANSFERTXRESPONSE
DESCRIPTOR.message_types_by_name['CreateRawDeployContractTxResponse'] = _CREATERAWDEPLOYCONTRACTTXRESPONSE
DESCRIPTOR.message_types_by_name['CreateRawValidatorTxResponse'] = _CREATERAWVALIDATORTXRESPONSE
DESCRIPTOR.message_types_by_name['CreateRawWithdrawTxResponse'] = _CREATERAWWITHDRAWTXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendTransactionResponse = _reflection.GeneratedProtocolMessageType('SendTransactionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDTRANSACTIONRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.SendTransactionResponse)
  })
_sym_db.RegisterMessage(SendTransactionResponse)

GetTransactionReceiptResponse = _reflection.GeneratedProtocolMessageType('GetTransactionReceiptResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSACTIONRECEIPTRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.GetTransactionReceiptResponse)
  })
_sym_db.RegisterMessage(GetTransactionReceiptResponse)

GetTransactionResponse = _reflection.GeneratedProtocolMessageType('GetTransactionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSACTIONRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.GetTransactionResponse)
  })
_sym_db.RegisterMessage(GetTransactionResponse)

CreateRawTransferTxResponse = _reflection.GeneratedProtocolMessageType('CreateRawTransferTxResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERAWTRANSFERTXRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.CreateRawTransferTxResponse)
  })
_sym_db.RegisterMessage(CreateRawTransferTxResponse)

CreateRawDeployContractTxResponse = _reflection.GeneratedProtocolMessageType('CreateRawDeployContractTxResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERAWDEPLOYCONTRACTTXRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.CreateRawDeployContractTxResponse)
  })
_sym_db.RegisterMessage(CreateRawDeployContractTxResponse)

CreateRawValidatorTxResponse = _reflection.GeneratedProtocolMessageType('CreateRawValidatorTxResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERAWVALIDATORTXRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.CreateRawValidatorTxResponse)
  })
_sym_db.RegisterMessage(CreateRawValidatorTxResponse)

CreateRawWithdrawTxResponse = _reflection.GeneratedProtocolMessageType('CreateRawWithdrawTxResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERAWWITHDRAWTXRESPONSE,
  '__module__' : 'qsn.entity.response.TransactionResponses_pb2'
  # @@protoc_insertion_point(class_scope:org.qsn.protobuf.CreateRawWithdrawTxResponse)
  })
_sym_db.RegisterMessage(CreateRawWithdrawTxResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
