// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/common/block/BlockDto.proto

package org.qsn.api.rpc.grpc.proto.entity.common.block;

public interface BlockHeaderDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.qsn.protobuf.BlockHeaderDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
   * @return The version.
   */
  org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto getVersion();
  /**
   * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
   */
  org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder getVersionOrBuilder();

  /**
   * <code>bytes blockAddress = 2;</code>
   * @return The blockAddress.
   */
  com.google.protobuf.ByteString getBlockAddress();

  /**
   * <code>string chainId = 3;</code>
   * @return The chainId.
   */
  java.lang.String getChainId();
  /**
   * <code>string chainId = 3;</code>
   * @return The bytes for chainId.
   */
  com.google.protobuf.ByteString
      getChainIdBytes();

  /**
   * <code>int64 height = 4;</code>
   * @return The height.
   */
  long getHeight();

  /**
   * <code>int64 time = 5;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>int64 numTxs = 6;</code>
   * @return The numTxs.
   */
  long getNumTxs();

  /**
   * <code>int64 totalTxs = 7;</code>
   * @return The totalTxs.
   */
  long getTotalTxs();

  /**
   * <code>int64 proposerSequenceNumber = 8;</code>
   * @return The proposerSequenceNumber.
   */
  long getProposerSequenceNumber();

  /**
   * <code>bytes lastBlockHash = 9;</code>
   * @return The lastBlockHash.
   */
  com.google.protobuf.ByteString getLastBlockHash();

  /**
   * <code>bytes lastCommitHash = 10;</code>
   * @return The lastCommitHash.
   */
  com.google.protobuf.ByteString getLastCommitHash();

  /**
   * <code>bytes dataHash = 11;</code>
   * @return The dataHash.
   */
  com.google.protobuf.ByteString getDataHash();

  /**
   * <code>bytes validatorsHash = 12;</code>
   * @return The validatorsHash.
   */
  com.google.protobuf.ByteString getValidatorsHash();

  /**
   * <code>bytes nextValidatorsHash = 13;</code>
   * @return The nextValidatorsHash.
   */
  com.google.protobuf.ByteString getNextValidatorsHash();

  /**
   * <code>bytes accountHash = 14;</code>
   * @return The accountHash.
   */
  com.google.protobuf.ByteString getAccountHash();

  /**
   * <code>bytes contractHash = 15;</code>
   * @return The contractHash.
   */
  com.google.protobuf.ByteString getContractHash();

  /**
   * <code>bytes storageHash = 16;</code>
   * @return The storageHash.
   */
  com.google.protobuf.ByteString getStorageHash();

  /**
   * <code>bytes transactionHash = 17;</code>
   * @return The transactionHash.
   */
  com.google.protobuf.ByteString getTransactionHash();

  /**
   * <code>bytes transactionReceiptHash = 18;</code>
   * @return The transactionReceiptHash.
   */
  com.google.protobuf.ByteString getTransactionReceiptHash();

  /**
   * <code>bytes blockRewardHash = 19;</code>
   * @return The blockRewardHash.
   */
  com.google.protobuf.ByteString getBlockRewardHash();

  /**
   * <code>bytes proposerAddress = 20;</code>
   * @return The proposerAddress.
   */
  com.google.protobuf.ByteString getProposerAddress();
}
