// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/common/block/BlockDto.proto

package org.qsn.api.rpc.grpc.proto.entity.common.block;

/**
 * Protobuf type {@code org.qsn.protobuf.BlockHeaderDto}
 */
public final class BlockHeaderDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.BlockHeaderDto)
    BlockHeaderDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockHeaderDto.newBuilder() to construct.
  private BlockHeaderDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockHeaderDto() {
    blockAddress_ = com.google.protobuf.ByteString.EMPTY;
    chainId_ = "";
    lastBlockHash_ = com.google.protobuf.ByteString.EMPTY;
    lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
    dataHash_ = com.google.protobuf.ByteString.EMPTY;
    validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    accountHash_ = com.google.protobuf.ByteString.EMPTY;
    contractHash_ = com.google.protobuf.ByteString.EMPTY;
    storageHash_ = com.google.protobuf.ByteString.EMPTY;
    transactionHash_ = com.google.protobuf.ByteString.EMPTY;
    transactionReceiptHash_ = com.google.protobuf.ByteString.EMPTY;
    blockRewardHash_ = com.google.protobuf.ByteString.EMPTY;
    proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockHeaderDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BlockHeaderDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder subBuilder = null;
            if (version_ != null) {
              subBuilder = version_.toBuilder();
            }
            version_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(version_);
              version_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {

            blockAddress_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            chainId_ = s;
            break;
          }
          case 32: {

            height_ = input.readInt64();
            break;
          }
          case 40: {

            time_ = input.readInt64();
            break;
          }
          case 48: {

            numTxs_ = input.readInt64();
            break;
          }
          case 56: {

            totalTxs_ = input.readInt64();
            break;
          }
          case 64: {

            proposerSequenceNumber_ = input.readInt64();
            break;
          }
          case 74: {

            lastBlockHash_ = input.readBytes();
            break;
          }
          case 82: {

            lastCommitHash_ = input.readBytes();
            break;
          }
          case 90: {

            dataHash_ = input.readBytes();
            break;
          }
          case 98: {

            validatorsHash_ = input.readBytes();
            break;
          }
          case 106: {

            nextValidatorsHash_ = input.readBytes();
            break;
          }
          case 114: {

            accountHash_ = input.readBytes();
            break;
          }
          case 122: {

            contractHash_ = input.readBytes();
            break;
          }
          case 130: {

            storageHash_ = input.readBytes();
            break;
          }
          case 138: {

            transactionHash_ = input.readBytes();
            break;
          }
          case 146: {

            transactionReceiptHash_ = input.readBytes();
            break;
          }
          case 154: {

            blockRewardHash_ = input.readBytes();
            break;
          }
          case 162: {

            proposerAddress_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.class, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto version_;
  /**
   * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto getVersion() {
    return version_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.getDefaultInstance() : version_;
  }
  /**
   * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder getVersionOrBuilder() {
    return getVersion();
  }

  public static final int BLOCKADDRESS_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString blockAddress_;
  /**
   * <code>bytes blockAddress = 2;</code>
   * @return The blockAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBlockAddress() {
    return blockAddress_;
  }

  public static final int CHAINID_FIELD_NUMBER = 3;
  private volatile java.lang.Object chainId_;
  /**
   * <code>string chainId = 3;</code>
   * @return The chainId.
   */
  @java.lang.Override
  public java.lang.String getChainId() {
    java.lang.Object ref = chainId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chainId_ = s;
      return s;
    }
  }
  /**
   * <code>string chainId = 3;</code>
   * @return The bytes for chainId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainIdBytes() {
    java.lang.Object ref = chainId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chainId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private long height_;
  /**
   * <code>int64 height = 4;</code>
   * @return The height.
   */
  @java.lang.Override
  public long getHeight() {
    return height_;
  }

  public static final int TIME_FIELD_NUMBER = 5;
  private long time_;
  /**
   * <code>int64 time = 5;</code>
   * @return The time.
   */
  @java.lang.Override
  public long getTime() {
    return time_;
  }

  public static final int NUMTXS_FIELD_NUMBER = 6;
  private long numTxs_;
  /**
   * <code>int64 numTxs = 6;</code>
   * @return The numTxs.
   */
  @java.lang.Override
  public long getNumTxs() {
    return numTxs_;
  }

  public static final int TOTALTXS_FIELD_NUMBER = 7;
  private long totalTxs_;
  /**
   * <code>int64 totalTxs = 7;</code>
   * @return The totalTxs.
   */
  @java.lang.Override
  public long getTotalTxs() {
    return totalTxs_;
  }

  public static final int PROPOSERSEQUENCENUMBER_FIELD_NUMBER = 8;
  private long proposerSequenceNumber_;
  /**
   * <code>int64 proposerSequenceNumber = 8;</code>
   * @return The proposerSequenceNumber.
   */
  @java.lang.Override
  public long getProposerSequenceNumber() {
    return proposerSequenceNumber_;
  }

  public static final int LASTBLOCKHASH_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString lastBlockHash_;
  /**
   * <code>bytes lastBlockHash = 9;</code>
   * @return The lastBlockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLastBlockHash() {
    return lastBlockHash_;
  }

  public static final int LASTCOMMITHASH_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString lastCommitHash_;
  /**
   * <code>bytes lastCommitHash = 10;</code>
   * @return The lastCommitHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLastCommitHash() {
    return lastCommitHash_;
  }

  public static final int DATAHASH_FIELD_NUMBER = 11;
  private com.google.protobuf.ByteString dataHash_;
  /**
   * <code>bytes dataHash = 11;</code>
   * @return The dataHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDataHash() {
    return dataHash_;
  }

  public static final int VALIDATORSHASH_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString validatorsHash_;
  /**
   * <code>bytes validatorsHash = 12;</code>
   * @return The validatorsHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValidatorsHash() {
    return validatorsHash_;
  }

  public static final int NEXTVALIDATORSHASH_FIELD_NUMBER = 13;
  private com.google.protobuf.ByteString nextValidatorsHash_;
  /**
   * <code>bytes nextValidatorsHash = 13;</code>
   * @return The nextValidatorsHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNextValidatorsHash() {
    return nextValidatorsHash_;
  }

  public static final int ACCOUNTHASH_FIELD_NUMBER = 14;
  private com.google.protobuf.ByteString accountHash_;
  /**
   * <code>bytes accountHash = 14;</code>
   * @return The accountHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAccountHash() {
    return accountHash_;
  }

  public static final int CONTRACTHASH_FIELD_NUMBER = 15;
  private com.google.protobuf.ByteString contractHash_;
  /**
   * <code>bytes contractHash = 15;</code>
   * @return The contractHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContractHash() {
    return contractHash_;
  }

  public static final int STORAGEHASH_FIELD_NUMBER = 16;
  private com.google.protobuf.ByteString storageHash_;
  /**
   * <code>bytes storageHash = 16;</code>
   * @return The storageHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStorageHash() {
    return storageHash_;
  }

  public static final int TRANSACTIONHASH_FIELD_NUMBER = 17;
  private com.google.protobuf.ByteString transactionHash_;
  /**
   * <code>bytes transactionHash = 17;</code>
   * @return The transactionHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTransactionHash() {
    return transactionHash_;
  }

  public static final int TRANSACTIONRECEIPTHASH_FIELD_NUMBER = 18;
  private com.google.protobuf.ByteString transactionReceiptHash_;
  /**
   * <code>bytes transactionReceiptHash = 18;</code>
   * @return The transactionReceiptHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTransactionReceiptHash() {
    return transactionReceiptHash_;
  }

  public static final int BLOCKREWARDHASH_FIELD_NUMBER = 19;
  private com.google.protobuf.ByteString blockRewardHash_;
  /**
   * <code>bytes blockRewardHash = 19;</code>
   * @return The blockRewardHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBlockRewardHash() {
    return blockRewardHash_;
  }

  public static final int PROPOSERADDRESS_FIELD_NUMBER = 20;
  private com.google.protobuf.ByteString proposerAddress_;
  /**
   * <code>bytes proposerAddress = 20;</code>
   * @return The proposerAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProposerAddress() {
    return proposerAddress_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != null) {
      output.writeMessage(1, getVersion());
    }
    if (!blockAddress_.isEmpty()) {
      output.writeBytes(2, blockAddress_);
    }
    if (!getChainIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, chainId_);
    }
    if (height_ != 0L) {
      output.writeInt64(4, height_);
    }
    if (time_ != 0L) {
      output.writeInt64(5, time_);
    }
    if (numTxs_ != 0L) {
      output.writeInt64(6, numTxs_);
    }
    if (totalTxs_ != 0L) {
      output.writeInt64(7, totalTxs_);
    }
    if (proposerSequenceNumber_ != 0L) {
      output.writeInt64(8, proposerSequenceNumber_);
    }
    if (!lastBlockHash_.isEmpty()) {
      output.writeBytes(9, lastBlockHash_);
    }
    if (!lastCommitHash_.isEmpty()) {
      output.writeBytes(10, lastCommitHash_);
    }
    if (!dataHash_.isEmpty()) {
      output.writeBytes(11, dataHash_);
    }
    if (!validatorsHash_.isEmpty()) {
      output.writeBytes(12, validatorsHash_);
    }
    if (!nextValidatorsHash_.isEmpty()) {
      output.writeBytes(13, nextValidatorsHash_);
    }
    if (!accountHash_.isEmpty()) {
      output.writeBytes(14, accountHash_);
    }
    if (!contractHash_.isEmpty()) {
      output.writeBytes(15, contractHash_);
    }
    if (!storageHash_.isEmpty()) {
      output.writeBytes(16, storageHash_);
    }
    if (!transactionHash_.isEmpty()) {
      output.writeBytes(17, transactionHash_);
    }
    if (!transactionReceiptHash_.isEmpty()) {
      output.writeBytes(18, transactionReceiptHash_);
    }
    if (!blockRewardHash_.isEmpty()) {
      output.writeBytes(19, blockRewardHash_);
    }
    if (!proposerAddress_.isEmpty()) {
      output.writeBytes(20, proposerAddress_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersion());
    }
    if (!blockAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, blockAddress_);
    }
    if (!getChainIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, chainId_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, height_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, time_);
    }
    if (numTxs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, numTxs_);
    }
    if (totalTxs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, totalTxs_);
    }
    if (proposerSequenceNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, proposerSequenceNumber_);
    }
    if (!lastBlockHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, lastBlockHash_);
    }
    if (!lastCommitHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, lastCommitHash_);
    }
    if (!dataHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, dataHash_);
    }
    if (!validatorsHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, validatorsHash_);
    }
    if (!nextValidatorsHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, nextValidatorsHash_);
    }
    if (!accountHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, accountHash_);
    }
    if (!contractHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(15, contractHash_);
    }
    if (!storageHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(16, storageHash_);
    }
    if (!transactionHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, transactionHash_);
    }
    if (!transactionReceiptHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(18, transactionReceiptHash_);
    }
    if (!blockRewardHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(19, blockRewardHash_);
    }
    if (!proposerAddress_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(20, proposerAddress_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto other = (org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto) obj;

    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (!getBlockAddress()
        .equals(other.getBlockAddress())) return false;
    if (!getChainId()
        .equals(other.getChainId())) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (getTime()
        != other.getTime()) return false;
    if (getNumTxs()
        != other.getNumTxs()) return false;
    if (getTotalTxs()
        != other.getTotalTxs()) return false;
    if (getProposerSequenceNumber()
        != other.getProposerSequenceNumber()) return false;
    if (!getLastBlockHash()
        .equals(other.getLastBlockHash())) return false;
    if (!getLastCommitHash()
        .equals(other.getLastCommitHash())) return false;
    if (!getDataHash()
        .equals(other.getDataHash())) return false;
    if (!getValidatorsHash()
        .equals(other.getValidatorsHash())) return false;
    if (!getNextValidatorsHash()
        .equals(other.getNextValidatorsHash())) return false;
    if (!getAccountHash()
        .equals(other.getAccountHash())) return false;
    if (!getContractHash()
        .equals(other.getContractHash())) return false;
    if (!getStorageHash()
        .equals(other.getStorageHash())) return false;
    if (!getTransactionHash()
        .equals(other.getTransactionHash())) return false;
    if (!getTransactionReceiptHash()
        .equals(other.getTransactionReceiptHash())) return false;
    if (!getBlockRewardHash()
        .equals(other.getBlockRewardHash())) return false;
    if (!getProposerAddress()
        .equals(other.getProposerAddress())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    hash = (37 * hash) + BLOCKADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getBlockAddress().hashCode();
    hash = (37 * hash) + CHAINID_FIELD_NUMBER;
    hash = (53 * hash) + getChainId().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + NUMTXS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumTxs());
    hash = (37 * hash) + TOTALTXS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalTxs());
    hash = (37 * hash) + PROPOSERSEQUENCENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProposerSequenceNumber());
    hash = (37 * hash) + LASTBLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getLastBlockHash().hashCode();
    hash = (37 * hash) + LASTCOMMITHASH_FIELD_NUMBER;
    hash = (53 * hash) + getLastCommitHash().hashCode();
    hash = (37 * hash) + DATAHASH_FIELD_NUMBER;
    hash = (53 * hash) + getDataHash().hashCode();
    hash = (37 * hash) + VALIDATORSHASH_FIELD_NUMBER;
    hash = (53 * hash) + getValidatorsHash().hashCode();
    hash = (37 * hash) + NEXTVALIDATORSHASH_FIELD_NUMBER;
    hash = (53 * hash) + getNextValidatorsHash().hashCode();
    hash = (37 * hash) + ACCOUNTHASH_FIELD_NUMBER;
    hash = (53 * hash) + getAccountHash().hashCode();
    hash = (37 * hash) + CONTRACTHASH_FIELD_NUMBER;
    hash = (53 * hash) + getContractHash().hashCode();
    hash = (37 * hash) + STORAGEHASH_FIELD_NUMBER;
    hash = (53 * hash) + getStorageHash().hashCode();
    hash = (37 * hash) + TRANSACTIONHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionHash().hashCode();
    hash = (37 * hash) + TRANSACTIONRECEIPTHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionReceiptHash().hashCode();
    hash = (37 * hash) + BLOCKREWARDHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockRewardHash().hashCode();
    hash = (37 * hash) + PROPOSERADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProposerAddress().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.BlockHeaderDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.BlockHeaderDto)
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.class, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (versionBuilder_ == null) {
        version_ = null;
      } else {
        version_ = null;
        versionBuilder_ = null;
      }
      blockAddress_ = com.google.protobuf.ByteString.EMPTY;

      chainId_ = "";

      height_ = 0L;

      time_ = 0L;

      numTxs_ = 0L;

      totalTxs_ = 0L;

      proposerSequenceNumber_ = 0L;

      lastBlockHash_ = com.google.protobuf.ByteString.EMPTY;

      lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;

      dataHash_ = com.google.protobuf.ByteString.EMPTY;

      validatorsHash_ = com.google.protobuf.ByteString.EMPTY;

      nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;

      accountHash_ = com.google.protobuf.ByteString.EMPTY;

      contractHash_ = com.google.protobuf.ByteString.EMPTY;

      storageHash_ = com.google.protobuf.ByteString.EMPTY;

      transactionHash_ = com.google.protobuf.ByteString.EMPTY;

      transactionReceiptHash_ = com.google.protobuf.ByteString.EMPTY;

      blockRewardHash_ = com.google.protobuf.ByteString.EMPTY;

      proposerAddress_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderDto_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto build() {
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto result = new org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto(this);
      if (versionBuilder_ == null) {
        result.version_ = version_;
      } else {
        result.version_ = versionBuilder_.build();
      }
      result.blockAddress_ = blockAddress_;
      result.chainId_ = chainId_;
      result.height_ = height_;
      result.time_ = time_;
      result.numTxs_ = numTxs_;
      result.totalTxs_ = totalTxs_;
      result.proposerSequenceNumber_ = proposerSequenceNumber_;
      result.lastBlockHash_ = lastBlockHash_;
      result.lastCommitHash_ = lastCommitHash_;
      result.dataHash_ = dataHash_;
      result.validatorsHash_ = validatorsHash_;
      result.nextValidatorsHash_ = nextValidatorsHash_;
      result.accountHash_ = accountHash_;
      result.contractHash_ = contractHash_;
      result.storageHash_ = storageHash_;
      result.transactionHash_ = transactionHash_;
      result.transactionReceiptHash_ = transactionReceiptHash_;
      result.blockRewardHash_ = blockRewardHash_;
      result.proposerAddress_ = proposerAddress_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (other.getBlockAddress() != com.google.protobuf.ByteString.EMPTY) {
        setBlockAddress(other.getBlockAddress());
      }
      if (!other.getChainId().isEmpty()) {
        chainId_ = other.chainId_;
        onChanged();
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getNumTxs() != 0L) {
        setNumTxs(other.getNumTxs());
      }
      if (other.getTotalTxs() != 0L) {
        setTotalTxs(other.getTotalTxs());
      }
      if (other.getProposerSequenceNumber() != 0L) {
        setProposerSequenceNumber(other.getProposerSequenceNumber());
      }
      if (other.getLastBlockHash() != com.google.protobuf.ByteString.EMPTY) {
        setLastBlockHash(other.getLastBlockHash());
      }
      if (other.getLastCommitHash() != com.google.protobuf.ByteString.EMPTY) {
        setLastCommitHash(other.getLastCommitHash());
      }
      if (other.getDataHash() != com.google.protobuf.ByteString.EMPTY) {
        setDataHash(other.getDataHash());
      }
      if (other.getValidatorsHash() != com.google.protobuf.ByteString.EMPTY) {
        setValidatorsHash(other.getValidatorsHash());
      }
      if (other.getNextValidatorsHash() != com.google.protobuf.ByteString.EMPTY) {
        setNextValidatorsHash(other.getNextValidatorsHash());
      }
      if (other.getAccountHash() != com.google.protobuf.ByteString.EMPTY) {
        setAccountHash(other.getAccountHash());
      }
      if (other.getContractHash() != com.google.protobuf.ByteString.EMPTY) {
        setContractHash(other.getContractHash());
      }
      if (other.getStorageHash() != com.google.protobuf.ByteString.EMPTY) {
        setStorageHash(other.getStorageHash());
      }
      if (other.getTransactionHash() != com.google.protobuf.ByteString.EMPTY) {
        setTransactionHash(other.getTransactionHash());
      }
      if (other.getTransactionReceiptHash() != com.google.protobuf.ByteString.EMPTY) {
        setTransactionReceiptHash(other.getTransactionReceiptHash());
      }
      if (other.getBlockRewardHash() != com.google.protobuf.ByteString.EMPTY) {
        setBlockRewardHash(other.getBlockRewardHash());
      }
      if (other.getProposerAddress() != com.google.protobuf.ByteString.EMPTY) {
        setProposerAddress(other.getProposerAddress());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto version_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder> versionBuilder_;
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return versionBuilder_ != null || version_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     * @return The version.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    public Builder setVersion(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
        onChanged();
      } else {
        versionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    public Builder setVersion(
        org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
        onChanged();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    public Builder mergeVersion(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto value) {
      if (versionBuilder_ == null) {
        if (version_ != null) {
          version_ =
            org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }
        onChanged();
      } else {
        versionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    public Builder clearVersion() {
      if (versionBuilder_ == null) {
        version_ = null;
        onChanged();
      } else {
        version_ = null;
        versionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder getVersionBuilder() {
      
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.getDefaultInstance() : version_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.BlockHeaderVersionDto version = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private com.google.protobuf.ByteString blockAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes blockAddress = 2;</code>
     * @return The blockAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBlockAddress() {
      return blockAddress_;
    }
    /**
     * <code>bytes blockAddress = 2;</code>
     * @param value The blockAddress to set.
     * @return This builder for chaining.
     */
    public Builder setBlockAddress(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes blockAddress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockAddress() {
      
      blockAddress_ = getDefaultInstance().getBlockAddress();
      onChanged();
      return this;
    }

    private java.lang.Object chainId_ = "";
    /**
     * <code>string chainId = 3;</code>
     * @return The chainId.
     */
    public java.lang.String getChainId() {
      java.lang.Object ref = chainId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chainId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chainId = 3;</code>
     * @return The bytes for chainId.
     */
    public com.google.protobuf.ByteString
        getChainIdBytes() {
      java.lang.Object ref = chainId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chainId = 3;</code>
     * @param value The chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chainId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chainId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChainId() {
      
      chainId_ = getDefaultInstance().getChainId();
      onChanged();
      return this;
    }
    /**
     * <code>string chainId = 3;</code>
     * @param value The bytes for chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chainId_ = value;
      onChanged();
      return this;
    }

    private long height_ ;
    /**
     * <code>int64 height = 4;</code>
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return height_;
    }
    /**
     * <code>int64 height = 4;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = 0L;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <code>int64 time = 5;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 5;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long numTxs_ ;
    /**
     * <code>int64 numTxs = 6;</code>
     * @return The numTxs.
     */
    @java.lang.Override
    public long getNumTxs() {
      return numTxs_;
    }
    /**
     * <code>int64 numTxs = 6;</code>
     * @param value The numTxs to set.
     * @return This builder for chaining.
     */
    public Builder setNumTxs(long value) {
      
      numTxs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 numTxs = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumTxs() {
      
      numTxs_ = 0L;
      onChanged();
      return this;
    }

    private long totalTxs_ ;
    /**
     * <code>int64 totalTxs = 7;</code>
     * @return The totalTxs.
     */
    @java.lang.Override
    public long getTotalTxs() {
      return totalTxs_;
    }
    /**
     * <code>int64 totalTxs = 7;</code>
     * @param value The totalTxs to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTxs(long value) {
      
      totalTxs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalTxs = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTxs() {
      
      totalTxs_ = 0L;
      onChanged();
      return this;
    }

    private long proposerSequenceNumber_ ;
    /**
     * <code>int64 proposerSequenceNumber = 8;</code>
     * @return The proposerSequenceNumber.
     */
    @java.lang.Override
    public long getProposerSequenceNumber() {
      return proposerSequenceNumber_;
    }
    /**
     * <code>int64 proposerSequenceNumber = 8;</code>
     * @param value The proposerSequenceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProposerSequenceNumber(long value) {
      
      proposerSequenceNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 proposerSequenceNumber = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProposerSequenceNumber() {
      
      proposerSequenceNumber_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString lastBlockHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes lastBlockHash = 9;</code>
     * @return The lastBlockHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLastBlockHash() {
      return lastBlockHash_;
    }
    /**
     * <code>bytes lastBlockHash = 9;</code>
     * @param value The lastBlockHash to set.
     * @return This builder for chaining.
     */
    public Builder setLastBlockHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastBlockHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes lastBlockHash = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastBlockHash() {
      
      lastBlockHash_ = getDefaultInstance().getLastBlockHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString lastCommitHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes lastCommitHash = 10;</code>
     * @return The lastCommitHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLastCommitHash() {
      return lastCommitHash_;
    }
    /**
     * <code>bytes lastCommitHash = 10;</code>
     * @param value The lastCommitHash to set.
     * @return This builder for chaining.
     */
    public Builder setLastCommitHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastCommitHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes lastCommitHash = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastCommitHash() {
      
      lastCommitHash_ = getDefaultInstance().getLastCommitHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString dataHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes dataHash = 11;</code>
     * @return The dataHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataHash() {
      return dataHash_;
    }
    /**
     * <code>bytes dataHash = 11;</code>
     * @param value The dataHash to set.
     * @return This builder for chaining.
     */
    public Builder setDataHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes dataHash = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataHash() {
      
      dataHash_ = getDefaultInstance().getDataHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString validatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes validatorsHash = 12;</code>
     * @return The validatorsHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValidatorsHash() {
      return validatorsHash_;
    }
    /**
     * <code>bytes validatorsHash = 12;</code>
     * @param value The validatorsHash to set.
     * @return This builder for chaining.
     */
    public Builder setValidatorsHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      validatorsHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes validatorsHash = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidatorsHash() {
      
      validatorsHash_ = getDefaultInstance().getValidatorsHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString nextValidatorsHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes nextValidatorsHash = 13;</code>
     * @return The nextValidatorsHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNextValidatorsHash() {
      return nextValidatorsHash_;
    }
    /**
     * <code>bytes nextValidatorsHash = 13;</code>
     * @param value The nextValidatorsHash to set.
     * @return This builder for chaining.
     */
    public Builder setNextValidatorsHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextValidatorsHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes nextValidatorsHash = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextValidatorsHash() {
      
      nextValidatorsHash_ = getDefaultInstance().getNextValidatorsHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString accountHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes accountHash = 14;</code>
     * @return The accountHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAccountHash() {
      return accountHash_;
    }
    /**
     * <code>bytes accountHash = 14;</code>
     * @param value The accountHash to set.
     * @return This builder for chaining.
     */
    public Builder setAccountHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes accountHash = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountHash() {
      
      accountHash_ = getDefaultInstance().getAccountHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString contractHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes contractHash = 15;</code>
     * @return The contractHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContractHash() {
      return contractHash_;
    }
    /**
     * <code>bytes contractHash = 15;</code>
     * @param value The contractHash to set.
     * @return This builder for chaining.
     */
    public Builder setContractHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes contractHash = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractHash() {
      
      contractHash_ = getDefaultInstance().getContractHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString storageHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes storageHash = 16;</code>
     * @return The storageHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStorageHash() {
      return storageHash_;
    }
    /**
     * <code>bytes storageHash = 16;</code>
     * @param value The storageHash to set.
     * @return This builder for chaining.
     */
    public Builder setStorageHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      storageHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes storageHash = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearStorageHash() {
      
      storageHash_ = getDefaultInstance().getStorageHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString transactionHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes transactionHash = 17;</code>
     * @return The transactionHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTransactionHash() {
      return transactionHash_;
    }
    /**
     * <code>bytes transactionHash = 17;</code>
     * @param value The transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes transactionHash = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionHash() {
      
      transactionHash_ = getDefaultInstance().getTransactionHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString transactionReceiptHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes transactionReceiptHash = 18;</code>
     * @return The transactionReceiptHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTransactionReceiptHash() {
      return transactionReceiptHash_;
    }
    /**
     * <code>bytes transactionReceiptHash = 18;</code>
     * @param value The transactionReceiptHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionReceiptHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionReceiptHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes transactionReceiptHash = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionReceiptHash() {
      
      transactionReceiptHash_ = getDefaultInstance().getTransactionReceiptHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString blockRewardHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes blockRewardHash = 19;</code>
     * @return The blockRewardHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBlockRewardHash() {
      return blockRewardHash_;
    }
    /**
     * <code>bytes blockRewardHash = 19;</code>
     * @param value The blockRewardHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockRewardHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockRewardHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes blockRewardHash = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockRewardHash() {
      
      blockRewardHash_ = getDefaultInstance().getBlockRewardHash();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString proposerAddress_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes proposerAddress = 20;</code>
     * @return The proposerAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProposerAddress() {
      return proposerAddress_;
    }
    /**
     * <code>bytes proposerAddress = 20;</code>
     * @param value The proposerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setProposerAddress(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proposerAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes proposerAddress = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearProposerAddress() {
      
      proposerAddress_ = getDefaultInstance().getProposerAddress();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.BlockHeaderDto)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.BlockHeaderDto)
  private static final org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockHeaderDto>
      PARSER = new com.google.protobuf.AbstractParser<BlockHeaderDto>() {
    @java.lang.Override
    public BlockHeaderDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BlockHeaderDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BlockHeaderDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockHeaderDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

