// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/common/block/BlockDto.proto

package org.qsn.api.rpc.grpc.proto.entity.common.block;

/**
 * Protobuf type {@code org.qsn.protobuf.BlockHeaderVersionDto}
 */
public final class BlockHeaderVersionDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.BlockHeaderVersionDto)
    BlockHeaderVersionDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockHeaderVersionDto.newBuilder() to construct.
  private BlockHeaderVersionDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockHeaderVersionDto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockHeaderVersionDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BlockHeaderVersionDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            block_ = input.readInt32();
            break;
          }
          case 16: {

            app_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderVersionDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderVersionDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.class, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder.class);
  }

  public static final int BLOCK_FIELD_NUMBER = 1;
  private int block_;
  /**
   * <code>int32 block = 1;</code>
   * @return The block.
   */
  @java.lang.Override
  public int getBlock() {
    return block_;
  }

  public static final int APP_FIELD_NUMBER = 2;
  private int app_;
  /**
   * <code>int32 app = 2;</code>
   * @return The app.
   */
  @java.lang.Override
  public int getApp() {
    return app_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (block_ != 0) {
      output.writeInt32(1, block_);
    }
    if (app_ != 0) {
      output.writeInt32(2, app_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (block_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, block_);
    }
    if (app_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, app_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto other = (org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto) obj;

    if (getBlock()
        != other.getBlock()) return false;
    if (getApp()
        != other.getApp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCK_FIELD_NUMBER;
    hash = (53 * hash) + getBlock();
    hash = (37 * hash) + APP_FIELD_NUMBER;
    hash = (53 * hash) + getApp();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.BlockHeaderVersionDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.BlockHeaderVersionDto)
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderVersionDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderVersionDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.class, org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      block_ = 0;

      app_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockDtoOuterClass.internal_static_org_qsn_protobuf_BlockHeaderVersionDto_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto build() {
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto result = new org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto(this);
      result.block_ = block_;
      result.app_ = app_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto.getDefaultInstance()) return this;
      if (other.getBlock() != 0) {
        setBlock(other.getBlock());
      }
      if (other.getApp() != 0) {
        setApp(other.getApp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int block_ ;
    /**
     * <code>int32 block = 1;</code>
     * @return The block.
     */
    @java.lang.Override
    public int getBlock() {
      return block_;
    }
    /**
     * <code>int32 block = 1;</code>
     * @param value The block to set.
     * @return This builder for chaining.
     */
    public Builder setBlock(int value) {
      
      block_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 block = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlock() {
      
      block_ = 0;
      onChanged();
      return this;
    }

    private int app_ ;
    /**
     * <code>int32 app = 2;</code>
     * @return The app.
     */
    @java.lang.Override
    public int getApp() {
      return app_;
    }
    /**
     * <code>int32 app = 2;</code>
     * @param value The app to set.
     * @return This builder for chaining.
     */
    public Builder setApp(int value) {
      
      app_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 app = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearApp() {
      
      app_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.BlockHeaderVersionDto)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.BlockHeaderVersionDto)
  private static final org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockHeaderVersionDto>
      PARSER = new com.google.protobuf.AbstractParser<BlockHeaderVersionDto>() {
    @java.lang.Override
    public BlockHeaderVersionDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BlockHeaderVersionDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BlockHeaderVersionDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockHeaderVersionDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.block.BlockHeaderVersionDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

