// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/response/ValidatorResponses.proto

package org.qsn.api.rpc.grpc.proto.entity.response;

/**
 * Protobuf type {@code org.qsn.protobuf.GetValidatorResponse}
 */
public final class GetValidatorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.qsn.protobuf.GetValidatorResponse)
    GetValidatorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetValidatorResponse.newBuilder() to construct.
  private GetValidatorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetValidatorResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetValidatorResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetValidatorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.qsn.api.rpc.grpc.proto.entity.common.Result.Builder subBuilder = null;
            if (result_ != null) {
              subBuilder = result_.toBuilder();
            }
            result_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.Result.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(result_);
              result_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.Builder subBuilder = null;
            if (validator_ != null) {
              subBuilder = validator_.toBuilder();
            }
            validator_ = input.readMessage(org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(validator_);
              validator_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.qsn.api.rpc.grpc.proto.entity.response.ValidatorResponses.internal_static_org_qsn_protobuf_GetValidatorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.qsn.api.rpc.grpc.proto.entity.response.ValidatorResponses.internal_static_org_qsn_protobuf_GetValidatorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.class, org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private org.qsn.api.rpc.grpc.proto.entity.common.Result result_;
  /**
   * <code>.org.qsn.protobuf.Result result = 1;</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return result_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.Result result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.Result getResult() {
    return result_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.Result.getDefaultInstance() : result_;
  }
  /**
   * <code>.org.qsn.protobuf.Result result = 1;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.ResultOrBuilder getResultOrBuilder() {
    return getResult();
  }

  public static final int VALIDATOR_FIELD_NUMBER = 2;
  private org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto validator_;
  /**
   * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
   * @return Whether the validator field is set.
   */
  @java.lang.Override
  public boolean hasValidator() {
    return validator_ != null;
  }
  /**
   * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
   * @return The validator.
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto getValidator() {
    return validator_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.getDefaultInstance() : validator_;
  }
  /**
   * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
   */
  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDtoOrBuilder getValidatorOrBuilder() {
    return getValidator();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (result_ != null) {
      output.writeMessage(1, getResult());
    }
    if (validator_ != null) {
      output.writeMessage(2, getValidator());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (result_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResult());
    }
    if (validator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValidator());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse)) {
      return super.equals(obj);
    }
    org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse other = (org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse) obj;

    if (hasResult() != other.hasResult()) return false;
    if (hasResult()) {
      if (!getResult()
          .equals(other.getResult())) return false;
    }
    if (hasValidator() != other.hasValidator()) return false;
    if (hasValidator()) {
      if (!getValidator()
          .equals(other.getValidator())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    if (hasValidator()) {
      hash = (37 * hash) + VALIDATOR_FIELD_NUMBER;
      hash = (53 * hash) + getValidator().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.qsn.protobuf.GetValidatorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.qsn.protobuf.GetValidatorResponse)
      org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.qsn.api.rpc.grpc.proto.entity.response.ValidatorResponses.internal_static_org_qsn_protobuf_GetValidatorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.qsn.api.rpc.grpc.proto.entity.response.ValidatorResponses.internal_static_org_qsn_protobuf_GetValidatorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.class, org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.Builder.class);
    }

    // Construct using org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resultBuilder_ == null) {
        result_ = null;
      } else {
        result_ = null;
        resultBuilder_ = null;
      }
      if (validatorBuilder_ == null) {
        validator_ = null;
      } else {
        validator_ = null;
        validatorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.qsn.api.rpc.grpc.proto.entity.response.ValidatorResponses.internal_static_org_qsn_protobuf_GetValidatorResponse_descriptor;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse getDefaultInstanceForType() {
      return org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse build() {
      org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse buildPartial() {
      org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse result = new org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse(this);
      if (resultBuilder_ == null) {
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      if (validatorBuilder_ == null) {
        result.validator_ = validator_;
      } else {
        result.validator_ = validatorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse) {
        return mergeFrom((org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse other) {
      if (other == org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse.getDefaultInstance()) return this;
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      if (other.hasValidator()) {
        mergeValidator(other.getValidator());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.qsn.api.rpc.grpc.proto.entity.common.Result result_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.Result, org.qsn.api.rpc.grpc.proto.entity.common.Result.Builder, org.qsn.api.rpc.grpc.proto.entity.common.ResultOrBuilder> resultBuilder_;
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return resultBuilder_ != null || result_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     * @return The result.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.Result getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.Result.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    public Builder setResult(org.qsn.api.rpc.grpc.proto.entity.common.Result value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    public Builder setResult(
        org.qsn.api.rpc.grpc.proto.entity.common.Result.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    public Builder mergeResult(org.qsn.api.rpc.grpc.proto.entity.common.Result value) {
      if (resultBuilder_ == null) {
        if (result_ != null) {
          result_ =
            org.qsn.api.rpc.grpc.proto.entity.common.Result.newBuilder(result_).mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        resultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = null;
        onChanged();
      } else {
        result_ = null;
        resultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.Result.Builder getResultBuilder() {
      
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.ResultOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.Result.getDefaultInstance() : result_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.Result result = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.Result, org.qsn.api.rpc.grpc.proto.entity.common.Result.Builder, org.qsn.api.rpc.grpc.proto.entity.common.ResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.Result, org.qsn.api.rpc.grpc.proto.entity.common.Result.Builder, org.qsn.api.rpc.grpc.proto.entity.common.ResultOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto validator_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto, org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.Builder, org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDtoOrBuilder> validatorBuilder_;
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     * @return Whether the validator field is set.
     */
    public boolean hasValidator() {
      return validatorBuilder_ != null || validator_ != null;
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     * @return The validator.
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto getValidator() {
      if (validatorBuilder_ == null) {
        return validator_ == null ? org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.getDefaultInstance() : validator_;
      } else {
        return validatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    public Builder setValidator(org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto value) {
      if (validatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        validator_ = value;
        onChanged();
      } else {
        validatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    public Builder setValidator(
        org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.Builder builderForValue) {
      if (validatorBuilder_ == null) {
        validator_ = builderForValue.build();
        onChanged();
      } else {
        validatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    public Builder mergeValidator(org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto value) {
      if (validatorBuilder_ == null) {
        if (validator_ != null) {
          validator_ =
            org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.newBuilder(validator_).mergeFrom(value).buildPartial();
        } else {
          validator_ = value;
        }
        onChanged();
      } else {
        validatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    public Builder clearValidator() {
      if (validatorBuilder_ == null) {
        validator_ = null;
        onChanged();
      } else {
        validator_ = null;
        validatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.Builder getValidatorBuilder() {
      
      onChanged();
      return getValidatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    public org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDtoOrBuilder getValidatorOrBuilder() {
      if (validatorBuilder_ != null) {
        return validatorBuilder_.getMessageOrBuilder();
      } else {
        return validator_ == null ?
            org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.getDefaultInstance() : validator_;
      }
    }
    /**
     * <code>.org.qsn.protobuf.ValidatorDto validator = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto, org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.Builder, org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDtoOrBuilder> 
        getValidatorFieldBuilder() {
      if (validatorBuilder_ == null) {
        validatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto, org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDto.Builder, org.qsn.api.rpc.grpc.proto.entity.common.account.ValidatorDtoOrBuilder>(
                getValidator(),
                getParentForChildren(),
                isClean());
        validator_ = null;
      }
      return validatorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.qsn.protobuf.GetValidatorResponse)
  }

  // @@protoc_insertion_point(class_scope:org.qsn.protobuf.GetValidatorResponse)
  private static final org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse();
  }

  public static org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetValidatorResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetValidatorResponse>() {
    @java.lang.Override
    public GetValidatorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetValidatorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetValidatorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetValidatorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.qsn.api.rpc.grpc.proto.entity.response.GetValidatorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

