// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qsn/entity/common/transaction/TransactionFeeDto.proto

package org.qsn.api.rpc.grpc.proto.entity.common.transaction;

public interface TransactionFeeDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.qsn.protobuf.TransactionFeeDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.qsn.protobuf.BInteger charge = 1;</code>
   * @return Whether the charge field is set.
   */
  boolean hasCharge();
  /**
   * <code>.org.qsn.protobuf.BInteger charge = 1;</code>
   * @return The charge.
   */
  org.qsn.api.rpc.grpc.proto.entity.common.BInteger getCharge();
  /**
   * <code>.org.qsn.protobuf.BInteger charge = 1;</code>
   */
  org.qsn.api.rpc.grpc.proto.entity.common.BIntegerOrBuilder getChargeOrBuilder();
}
